(()=>{
  const data=window.TOOLBOX_INTERIOR_STANDARDS_V314Y;
  if(!Array.isArray(data)) return;
  const extra=[
    {id:'int318-kitchen-counter-elbow',cat:'kuchyne',status:'DOPORUČENÍ',title:'Pracovní deska podle výšky lokte',recommended:'cca 100–150 mm pod loktem',minimum:'Přizpůsobit hlavnímu uživateli.',note:'Praktičtější než pevná univerzální výška; pro většinu dospělých vychází pracovní deska přibližně 850–950 mm.',keywords:['kuchyně','pracovní deska','ergonomie','loket','výška']},
    {id:'int318-kitchen-prep-zone',cat:'kuchyne',status:'DOPORUČENÍ',title:'Souvislá přípravná plocha',recommended:'min. cca 800–1200 mm',minimum:'cca 600 mm',note:'Nejužitečnější mezi dřezem a varnou deskou.',keywords:['kuchyně','příprava','pracovní plocha','dřez','varná deska']},
    {id:'int318-kitchen-sink-hob',cat:'kuchyne',status:'DOPORUČENÍ',title:'Odstup dřezu a varné desky',recommended:'600–1200 mm pracovní plochy',minimum:'cca 400 mm',note:'Mezera slouží jako hlavní přípravná zóna; příliš velká vzdálenost zhoršuje pracovní tok.',keywords:['kuchyně','dřez','varná deska','odstup']},
    {id:'int318-kitchen-hob-side',cat:'kuchyne',status:'DOPORUČENÍ',title:'Odkládací plocha vedle varné desky',recommended:'min. 300 mm na každé straně',minimum:'alespoň na jedné straně 300 mm',note:'Pomáhá bezpečně odkládat hrnce a náčiní.',keywords:['varná deska','odkládací plocha','kuchyně']},
    {id:'int318-kitchen-sink-side',cat:'kuchyne',status:'DOPORUČENÍ',title:'Odkládací plocha vedle dřezu',recommended:'450–600 mm',minimum:'cca 300 mm',note:'Praktické pro nádobí, přípravu a odkapávání.',keywords:['dřez','odkládací plocha','kuchyně']},
    {id:'int318-kitchen-fridge-side',cat:'kuchyne',status:'DOPORUČENÍ',title:'Odkládací plocha u lednice',recommended:'cca 400–600 mm v dosahu',minimum:'krátká plocha nebo pracovní deska poblíž',note:'Umožní položit nákup nebo potraviny při vykládání.',keywords:['lednice','odkládací plocha','kuchyně']},
    {id:'int318-kitchen-island-clearance',cat:'kuchyne',status:'DOPORUČENÍ',title:'Mezera kolem kuchyňského ostrůvku',recommended:'1000–1200 mm',minimum:'cca 900 mm',note:'U protilehlých spotřebičů nebo práce dvou osob je vhodné 1100–1300 mm.',keywords:['ostrůvek','průchod','kuchyně','mezera']},
    {id:'int318-kitchen-two-cooks',cat:'kuchyne',status:'DOPORUČENÍ',title:'Pracovní ulička pro dvě osoby',recommended:'1200–1400 mm',minimum:'cca 1100 mm',note:'Pro současnou práci a otevírání zásuvek na obou stranách.',keywords:['kuchyně','ulička','dvě osoby','průchod']},
    {id:'int318-kitchen-seating-knee',cat:'kuchyne',status:'DOPORUČENÍ',title:'Prostor pro kolena u ostrůvku',recommended:'hloubka 300–400 mm',minimum:'cca 250 mm',note:'Záleží na výšce sezení a tloušťce desky.',keywords:['ostrůvek','sezení','kolena','přesah']},
    {id:'int318-kitchen-bar-width',cat:'kuchyne',status:'DOPORUČENÍ',title:'Šířka místa na osobu u baru',recommended:'550–650 mm/osoba',minimum:'cca 500 mm',note:'Pro pohodlné lokty je lepší kolem 600 mm a více.',keywords:['bar','sezení','šířka','osoba','kuchyně']},
    {id:'int318-kitchen-oven-height',cat:'kuchyne',status:'DOPORUČENÍ',title:'Vestavná trouba ve zvýšené poloze',recommended:'střed pracovní zóny cca 900–1200 mm',minimum:'podle typu spotřebiče',note:'Vyšší montáž omezuje hluboké předklánění; ověř montážní pokyny výrobce.',keywords:['trouba','výška','kuchyně','ergonomie']},
    {id:'int318-kitchen-microwave-height',cat:'kuchyne',status:'DOPORUČENÍ',title:'Výška mikrovlnné trouby',recommended:'spodní hrana cca 900–1300 mm',minimum:'ovládání a nádoba v bezpečném dosahu',note:'Nedávat příliš vysoko kvůli manipulaci s horkým obsahem.',keywords:['mikrovlnka','výška','kuchyně']},
    {id:'int318-kitchen-plinth',cat:'kuchyne',status:'BĚŽNÝ ROZMĚR',title:'Sokl kuchyňské linky',recommended:'80–150 mm',minimum:'podle systému nábytku',note:'Ustoupení soklu zlepšuje prostor pro špičky chodidel.',keywords:['kuchyně','sokl','linka','rozměr']},
    {id:'int318-kitchen-wall-gap',cat:'kuchyne',status:'DOPORUČENÍ',title:'Mezera pracovní deska – horní skříňky',recommended:'500–650 mm',minimum:'podle spotřebičů a dosahu',note:'U varné desky a digestoře vždy respektuj výrobce spotřebičů.',keywords:['kuchyně','horní skříňky','mezera','výška']},

    {id:'int318-bath-double-basin',cat:'koupelna',status:'DOPORUČENÍ',title:'Šířka desky pro dvě umyvadla',recommended:'1200–1600 mm',minimum:'cca 1100 mm',note:'Komfortní rozteč os umyvadel bývá přibližně 600–750 mm.',keywords:['koupelna','umyvadlo','dvojité','šířka']},
    {id:'int318-bath-basin-axis',cat:'koupelna',status:'DOPORUČENÍ',title:'Osa umyvadla od boční stěny',recommended:'min. cca 450 mm',minimum:'podle šířky umyvadla',note:'Větší odstup zvyšuje prostor pro lokty a úklid.',keywords:['umyvadlo','stěna','osa','odstup']},
    {id:'int318-bath-shower-comfort',cat:'koupelna',status:'DOPORUČENÍ',title:'Komfortní sprchový kout',recommended:'900 × 1000 až 1000 × 1200 mm',minimum:'cca 800 × 800 mm',note:'Pro walk-in a snadnější pohyb je vhodné 900 mm a více v kratším směru.',keywords:['sprcha','walk-in','rozměr','koupelna']},
    {id:'int318-bath-shower-entry',cat:'koupelna',status:'DOPORUČENÍ',title:'Vstup do walk-in sprchy',recommended:'600–800 mm',minimum:'cca 550 mm',note:'Zohledni směr proudu vody a polohu pevné zástěny.',keywords:['sprcha','walk-in','vstup','šířka']},
    {id:'int318-bath-tub-size',cat:'koupelna',status:'BĚŽNÝ ROZMĚR',title:'Běžný rozměr vany',recommended:'1600–1800 × 700–800 mm',minimum:'kompaktní vany cca 1400 mm délky',note:'Skutečná ergonomie závisí na vnitřním profilu vany.',keywords:['vana','rozměr','koupelna']},
    {id:'int318-bath-wc-axis',cat:'koupelna',status:'DOPORUČENÍ',title:'Osa WC od boční stěny',recommended:'400–450 mm',minimum:'kompaktně cca 380 mm',note:'Pro bezbariérové WC platí jiné požadavky a větší manipulační prostor.',keywords:['wc','toaleta','osa','stěna','koupelna']},
    {id:'int318-bath-wc-front',cat:'koupelna',status:'DOPORUČENÍ',title:'Volný prostor před WC',recommended:'700–900 mm',minimum:'cca 600 mm',note:'Pokud je před WC dveřní křídlo nebo umyvadlo, ověř kolize.',keywords:['wc','toaleta','prostor před','koupelna']},
    {id:'int318-bath-basin-front',cat:'koupelna',status:'DOPORUČENÍ',title:'Volný prostor před umyvadlem',recommended:'800–1000 mm',minimum:'cca 700 mm',note:'U dvojice umyvadel nebo frekventované koupelny zvaž více.',keywords:['umyvadlo','prostor před','koupelna']},
    {id:'int318-bath-washer-front',cat:'koupelna',status:'DOPORUČENÍ',title:'Manipulační prostor před pračkou',recommended:'800–1000 mm',minimum:'cca 700 mm',note:'Před plněním zepředu musí být místo i na otevřená dvířka a koš.',keywords:['pračka','prádelna','prostor','koupelna']},
    {id:'int318-bath-mirror',cat:'koupelna',status:'DOPORUČENÍ',title:'Výška zrcadla nad umyvadlem',recommended:'spodní hrana cca 1000–1200 mm',minimum:'přizpůsobit uživatelům',note:'Důležitější je rozsah odrazu než jedna pevná montážní výška.',keywords:['zrcadlo','umyvadlo','výška','koupelna']},
    {id:'int318-bath-accessory',cat:'koupelna',status:'DOPORUČENÍ',title:'Dosah koupelnových doplňků',recommended:'900–1400 mm nad podlahou',minimum:'podle uživatele',note:'Ručníky, háčky a ovladače umisťuj do dosahu bez natahování přes mokrou zónu.',keywords:['ručník','háček','dosah','koupelna']},

    {id:'int318-storage-wardrobe',cat:'ulozne',status:'BĚŽNÝ ROZMĚR',title:'Hloubka šatní skříně',recommended:'600–650 mm',minimum:'cca 550 mm',note:'Posuvné dveře zvyšují celkovou potřebnou hloubku.',keywords:['skříň','šatna','hloubka','ramínka']},
    {id:'int318-storage-coats',cat:'ulozne',status:'DOPORUČENÍ',title:'Výška pro dlouhé kabáty a šaty',recommended:'1400–1700 mm',minimum:'podle délky oděvů',note:'Pro košile a saka lze použít dvě tyče nad sebou.',keywords:['šatna','kabát','šaty','tyč','výška']},
    {id:'int318-storage-shirts',cat:'ulozne',status:'DOPORUČENÍ',title:'Výška pro košile a saka',recommended:'900–1100 mm',minimum:'cca 850 mm',note:'Umožňuje dvě závěsné úrovně v jedné vysoké skříni.',keywords:['šatna','košile','sako','tyč']},
    {id:'int318-storage-shelves',cat:'ulozne',status:'DOPORUČENÍ',title:'Rozteč polic na oblečení',recommended:'250–350 mm',minimum:'podle ukládaných věcí',note:'Menší rozteč omezuje vysoké a nestabilní komínky oblečení.',keywords:['police','oblečení','skříň','rozteč']},
    {id:'int318-storage-books',cat:'ulozne',status:'BĚŽNÝ ROZMĚR',title:'Hloubka knihovny',recommended:'250–320 mm',minimum:'cca 200 mm pro malé knihy',note:'Šanony a velké obrazové knihy potřebují zhruba 300–350 mm.',keywords:['knihovna','police','hloubka','knihy']},
    {id:'int318-storage-shoes',cat:'ulozne',status:'BĚŽNÝ ROZMĚR',title:'Hloubka botníku',recommended:'320–400 mm',minimum:'cca 250 mm u výklopného systému',note:'Ověř největší velikost obuvi domácnosti.',keywords:['botník','obuv','hloubka','předsíň']},
    {id:'int318-storage-drawer',cat:'ulozne',status:'DOPORUČENÍ',title:'Praktická výška zásuvek ve skříni',recommended:'cca 150–250 mm čelo',minimum:'podle obsahu',note:'Nízké zásuvky jsou vhodné na drobnosti, vyšší na objemnější textil.',keywords:['zásuvka','skříň','výška','úložné']},
    {id:'int318-storage-upper-reach',cat:'ulozne',status:'DOPORUČENÍ',title:'Horní pohodlně dosažitelná police',recommended:'cca 1700–1800 mm',minimum:'nad touto úrovní spíše sezónní věci',note:'Výška se výrazně liší podle postavy uživatele.',keywords:['police','dosah','výška','skříň']},

    {id:'int318-entry-bench',cat:'predsin',status:'DOPORUČENÍ',title:'Výška lavice v předsíni',recommended:'430–480 mm',minimum:'cca 400 mm',note:'Pro pohodlné obouvání je vhodná výška podobná běžné židli.',keywords:['předsíň','lavice','obouvání','výška']},
    {id:'int318-entry-bench-depth',cat:'predsin',status:'DOPORUČENÍ',title:'Hloubka lavice v předsíni',recommended:'350–450 mm',minimum:'cca 300 mm',note:'Větší hloubka je pohodlnější, ale zabírá průchod.',keywords:['předsíň','lavice','hloubka']},
    {id:'int318-entry-clear',cat:'predsin',status:'DOPORUČENÍ',title:'Volný průchod v předsíni',recommended:'1000–1200 mm',minimum:'cca 900 mm',note:'Při otevírání skříní nebo vstupních dveří je vhodné více.',keywords:['předsíň','průchod','chodba','šířka']},
    {id:'int318-entry-coat',cat:'predsin',status:'DOPORUČENÍ',title:'Výška věšáků pro dospělé',recommended:'1500–1700 mm',minimum:'podle uživatelů',note:'Dětské háčky je vhodné doplnit výrazně níže.',keywords:['věšák','předsíň','výška','kabát']},
    {id:'int318-entry-mirror',cat:'predsin',status:'DOPORUČENÍ',title:'Celopostavové zrcadlo',recommended:'výška cca 1600–1800 mm',minimum:'cca 1400 mm',note:'Spodní hranu lze dát téměř k podlaze pro lepší využití různě vysokými osobami.',keywords:['zrcadlo','předsíň','výška']},

    {id:'int318-bed-side',cat:'loznice',status:'DOPORUČENÍ',title:'Průchod po straně postele',recommended:'700–900 mm',minimum:'cca 600 mm',note:'U jedné neobsluhované strany může být méně; u skříně je vhodné více.',keywords:['postel','ložnice','průchod','odstup']},
    {id:'int318-bed-foot',cat:'loznice',status:'DOPORUČENÍ',title:'Průchod u nohou postele',recommended:'800–1000 mm',minimum:'cca 600–700 mm',note:'Pokud je proti posteli skříň, zohledni její otevírání.',keywords:['postel','ložnice','průchod','nohy']},
    {id:'int318-bed-double',cat:'loznice',status:'BĚŽNÝ ROZMĚR',title:'Dvoulůžko',recommended:'1600–1800 × 2000 mm',minimum:'kompaktně 1400 × 2000 mm',note:'Rozměr matrace nezahrnuje rám postele.',keywords:['postel','dvoulůžko','ložnice','rozměr']},
    {id:'int318-bed-single',cat:'loznice',status:'BĚŽNÝ ROZMĚR',title:'Jednolůžko',recommended:'900–1000 × 2000 mm',minimum:'cca 800 × 2000 mm',note:'Pro dlouhodobé spaní je 900 mm šířky komfortnější.',keywords:['postel','jednolůžko','ložnice','rozměr']},
    {id:'int318-bed-nightstand',cat:'loznice',status:'DOPORUČENÍ',title:'Výška nočního stolku',recommended:'přibližně v úrovni horní hrany matrace',minimum:'±100 mm',note:'Usnadňuje dosah vleže.',keywords:['noční stolek','postel','výška','ložnice']},
    {id:'int318-bed-wardrobe',cat:'loznice',status:'DOPORUČENÍ',title:'Prostor před šatní skříní',recommended:'900–1100 mm',minimum:'cca 800 mm',note:'U otočných dveří nebo zásuvek zvaž 1000 mm a více.',keywords:['ložnice','skříň','prostor před','průchod']},

    {id:'int318-living-sofa-table',cat:'obyvak',status:'DOPORUČENÍ',title:'Mezera sedačka – konferenční stolek',recommended:'400–500 mm',minimum:'cca 350 mm',note:'Umožní dosah na stolek a současně průchod nohou.',keywords:['sedačka','stolek','obývák','odstup']},
    {id:'int318-living-main-passage',cat:'obyvak',status:'DOPORUČENÍ',title:'Hlavní průchod obývacím pokojem',recommended:'900–1200 mm',minimum:'cca 800 mm',note:'Hlavní komunikační trasa by neměla vést těsně přes sedací zónu.',keywords:['obývák','průchod','komunikace']},
    {id:'int318-living-tv',cat:'obyvak',status:'DOPORUČENÍ',title:'Pozorovací vzdálenost TV',recommended:'orientačně 1,2–1,8× úhlopříčka pro 4K',minimum:'podle rozlišení a preference',note:'Jde o orientační komfortní rozsah, ne závaznou normu.',keywords:['tv','televize','obývák','vzdálenost']},
    {id:'int318-living-tv-height',cat:'obyvak',status:'DOPORUČENÍ',title:'Výška středu TV',recommended:'přibližně v úrovni očí vsedě',minimum:'cca 950–1150 mm dle sezení',note:'Příliš vysoká obrazovka zvyšuje záklon krku.',keywords:['tv','televize','výška','obývák']},
    {id:'int318-living-armchair',cat:'obyvak',status:'DOPORUČENÍ',title:'Manipulační plocha kolem křesla',recommended:'cca 700–900 mm před sedákem',minimum:'cca 600 mm',note:'U relaxačního křesla ověř vysunutí podnožky.',keywords:['křeslo','obývák','prostor','průchod']},

    {id:'int318-dining-chair',cat:'jidlo',status:'DOPORUČENÍ',title:'Šířka místa u jídelního stolu',recommended:'600 mm/osoba',minimum:'cca 500–550 mm',note:'Pro komfortní lokty a prostírání počítej spíše 600 mm a více.',keywords:['jídelna','stůl','židle','osoba','šířka']},
    {id:'int318-dining-depth',cat:'jidlo',status:'DOPORUČENÍ',title:'Hloubka stolu pro dvě osoby proti sobě',recommended:'800–1000 mm',minimum:'cca 750 mm',note:'Větší hloubka umožní servírovací zónu uprostřed.',keywords:['jídelní stůl','hloubka','jídelna']},
    {id:'int318-dining-behind-chair',cat:'jidlo',status:'DOPORUČENÍ',title:'Prostor za jídelní židlí',recommended:'900–1100 mm',minimum:'cca 750 mm',note:'Pokud za sedící osobou vede průchod, počítej spíše 1100–1200 mm.',keywords:['jídelna','židle','průchod','stůl']},
    {id:'int318-dining-table-height',cat:'jidlo',status:'BĚŽNÝ ROZMĚR',title:'Výška jídelního stolu',recommended:'740–760 mm',minimum:'podle židlí',note:'Běžná výška pro standardní jídelní židle se sedákem kolem 430–470 mm.',keywords:['jídelní stůl','výška','jídelna']},
    {id:'int318-dining-seat-height',cat:'jidlo',status:'BĚŽNÝ ROZMĚR',title:'Výška sedáku jídelní židle',recommended:'430–470 mm',minimum:'podle výšky stolu',note:'Rozdíl mezi sedákem a horní deskou bývá přibližně 270–320 mm.',keywords:['židle','sedák','výška','jídelna']},

    {id:'int318-office-desk-height',cat:'pracovna',status:'DOPORUČENÍ',title:'Výška pracovního stolu',recommended:'cca 720–760 mm',minimum:'ideálně výškově nastavitelné řešení',note:'Pevná výška musí odpovídat židli a postavě uživatele.',keywords:['pracovna','stůl','výška','ergonomie']},
    {id:'int318-office-desk-depth',cat:'pracovna',status:'DOPORUČENÍ',title:'Hloubka pracovního stolu s monitorem',recommended:'700–800 mm',minimum:'cca 600 mm',note:'Více monitorů a velké displeje mohou vyžadovat větší hloubku.',keywords:['pracovna','stůl','monitor','hloubka']},
    {id:'int318-office-desk-width',cat:'pracovna',status:'DOPORUČENÍ',title:'Šířka pracovního místa',recommended:'1200–1600 mm',minimum:'cca 1000 mm',note:'Pro dva monitory nebo práci s výkresy je vhodné více.',keywords:['pracovna','stůl','šířka','pracovní místo']},
    {id:'int318-office-chair-clear',cat:'pracovna',status:'DOPORUČENÍ',title:'Prostor za pracovní židlí',recommended:'900–1200 mm',minimum:'cca 800 mm',note:'Je-li za židlí hlavní průchod, zvětši na 1200 mm a více.',keywords:['pracovna','židle','průchod','prostor']},
    {id:'int318-office-monitor',cat:'pracovna',status:'DOPORUČENÍ',title:'Vzdálenost očí od monitoru',recommended:'cca 500–800 mm',minimum:'podle velikosti displeje',note:'Horní část obrazovky bývá vhodná přibližně v úrovni očí nebo mírně pod ní.',keywords:['monitor','pracovna','vzdálenost','ergonomie']},
    {id:'int318-office-standing',cat:'pracovna',status:'DOPORUČENÍ',title:'Výška stolu pro práci ve stoje',recommended:'pracovní plocha přibližně v úrovni loktů',minimum:'výškově nastavitelné řešení',note:'Rozsah elektrických stolů často pokryje přibližně 650–1250 mm.',keywords:['stůl','stání','pracovna','výškově nastavitelný']},

    {id:'int318-retail-aisle',cat:'retail',status:'DOPORUČENÍ',title:'Běžná ulička mezi regály',recommended:'1200–1500 mm',minimum:'cca 1000 mm podle provozu',note:'Pro obousměrný pohyb s košíky nebo vozíky navrhuj více.',keywords:['retail','obchod','regál','ulička','průchod']},
    {id:'int318-retail-display',cat:'retail',status:'DOPORUČENÍ',title:'Hlavní zóna pohodlného dosahu zboží',recommended:'cca 700–1600 mm nad podlahou',minimum:'podle cílové skupiny',note:'Nejprodávanější zboží bývá vhodné umístit do snadno viditelného a dosažitelného pásma.',keywords:['retail','regál','zboží','dosah','výška']},
    {id:'int318-retail-counter',cat:'retail',status:'DOPORUČENÍ',title:'Výška prodejního pultu',recommended:'900–1100 mm',minimum:'podle typu obsluhy',note:'Pro přístupné řešení doplň sníženou část podle požadavků přístupnosti.',keywords:['retail','pult','výška','obchod']},
    {id:'int318-retail-fitting',cat:'retail',status:'DOPORUČENÍ',title:'Zkušební kabina – komfortní půdorys',recommended:'cca 1200 × 1200 mm a více',minimum:'kompaktně cca 1000 × 1000 mm',note:'Přístupná kabina vyžaduje výrazně větší manipulační prostor.',keywords:['retail','kabina','zkoušení','rozměr']},

    {id:'int318-gastro-table-person',cat:'gastro',status:'DOPORUČENÍ',title:'Šířka stolu na jednoho hosta',recommended:'600 mm/osoba',minimum:'cca 500 mm',note:'Fine dining a širší servis obvykle vyžaduje 650–750 mm na osobu.',keywords:['gastro','restaurace','stůl','host','šířka']},
    {id:'int318-gastro-service-aisle',cat:'gastro',status:'DOPORUČENÍ',title:'Servisní ulička v restauraci',recommended:'900–1200 mm',minimum:'cca 800 mm',note:'V hlavní obslužné trase nebo při obousměrném provozu navrhuj více.',keywords:['gastro','restaurace','ulička','obsluha']},
    {id:'int318-gastro-chair-back',cat:'gastro',status:'DOPORUČENÍ',title:'Prostor za obsazenou židlí',recommended:'450–600 mm bez průchodu',minimum:'cca 400 mm',note:'Pokud za hostem prochází obsluha, celková mezera od hrany stolu ke překážce má být výrazně větší.',keywords:['gastro','židle','restaurace','odstup']},
    {id:'int318-gastro-bar-height',cat:'gastro',status:'BĚŽNÝ ROZMĚR',title:'Výška barového pultu',recommended:'1050–1150 mm',minimum:'podle typu barové židle',note:'Pro klasické židle lze použít nižší jídelní část.',keywords:['bar','gastro','pult','výška']},
    {id:'int318-gastro-bar-seat',cat:'gastro',status:'BĚŽNÝ ROZMĚR',title:'Výška sedáku barové židle',recommended:'750–800 mm',minimum:'podle výšky pultu',note:'Mezi sedákem a deskou nech přibližně 250–300 mm.',keywords:['bar','židle','sedák','výška']},

    {id:'int318-hotel-bed-side',cat:'hotel',status:'DOPORUČENÍ',title:'Průchod kolem hotelového lůžka',recommended:'700–900 mm',minimum:'cca 600 mm',note:'Přístupné pokoje vyžadují větší manipulační prostor.',keywords:['hotel','postel','průchod','pokoj']},
    {id:'int318-hotel-luggage',cat:'hotel',status:'DOPORUČENÍ',title:'Odkládací plocha na kufr',recommended:'cca 600–900 × 450–550 mm',minimum:'dle standardu hotelu',note:'Výška kolem 450–600 mm usnadňuje manipulaci s kufrem.',keywords:['hotel','kufr','zavazadlo','odkládací plocha']},
    {id:'int318-hotel-desk',cat:'hotel',status:'DOPORUČENÍ',title:'Pracovní plocha v hotelovém pokoji',recommended:'šířka 900–1200 mm, hloubka 500–650 mm',minimum:'podle kategorie pokoje',note:'Zohledni zásuvky, světlo a prostor pro židli.',keywords:['hotel','stůl','pokoj','pracovní plocha']},

    {id:'int318-kids-table',cat:'deti',status:'DOPORUČENÍ',title:'Dětský stůl – výška podle věku',recommended:'cca 460–640 mm',minimum:'volit podle tělesné výšky dítěte',note:'U dětského nábytku je vhodnější řídit se velikostní řadou než jednou univerzální výškou.',keywords:['děti','stůl','výška','ergonomie']},
    {id:'int318-kids-seat',cat:'deti',status:'DOPORUČENÍ',title:'Dětská židle – výška sedáku',recommended:'cca 260–380 mm',minimum:'volit podle tělesné výšky',note:'Chodidla mají mít oporu a kolena přibližně pravý úhel.',keywords:['děti','židle','sedák','výška']},
    {id:'int318-kids-reach',cat:'deti',status:'DOPORUČENÍ',title:'Dosažitelné police pro děti',recommended:'cca 500–1200 mm podle věku',minimum:'nejčastější věci do spodní části',note:'Horní police vyhraď věcem obsluhovaným dospělým.',keywords:['děti','police','dosah','výška']},

    {id:'int318-school-desk-gap',cat:'skoly',status:'DOPORUČENÍ',title:'Průchod mezi řadami lavic',recommended:'cca 700–900 mm',minimum:'podle uspořádání třídy',note:'Hlavní komunikační trasy a přístupné třídy mohou vyžadovat více.',keywords:['škola','lavice','průchod','třída']},
    {id:'int318-school-board',cat:'skoly',status:'DOPORUČENÍ',title:'Spodní hrana školní tabule',recommended:'cca 700–900 mm',minimum:'přizpůsobit věku žáků',note:'Výška musí umožnit využití celé plochy tabule cílovou věkovou skupinou.',keywords:['škola','tabule','výška','třída']},
    {id:'int318-school-storage',cat:'skoly',status:'DOPORUČENÍ',title:'Výška otevřených úložných prvků pro žáky',recommended:'cca 600–1500 mm podle věku',minimum:'běžně používané věci v dosahu',note:'Rozsah přizpůsob věkové skupině a bezpečnosti.',keywords:['škola','police','úložné','dosah']},

    {id:'int318-general-passage-comfort',cat:'obecne',status:'DOPORUČENÍ',title:'Komfortní průchod pro jednu osobu',recommended:'900–1000 mm',minimum:'cca 800 mm mimo zvláštní předpisy',note:'Pro hlavní komunikace, míjení a přístupnost mohou platit větší požadavky.',keywords:['průchod','šířka','ergonomie','chodba']},
    {id:'int318-general-two-people',cat:'obecne',status:'DOPORUČENÍ',title:'Průchod pro pohodlné míjení dvou osob',recommended:'1200–1500 mm',minimum:'cca 1100 mm',note:'S taškami, vozíkem nebo v komerčním provozu je vhodné více.',keywords:['průchod','míjení','šířka','dvě osoby']},
    {id:'int318-general-door-handle',cat:'obecne',status:'DOPORUČENÍ',title:'Výška dveřní kliky',recommended:'cca 900–1100 mm',minimum:'podle systému a uživatelů',note:'V přístupných stavbách ověř požadavky na dosah a ovladatelnost.',keywords:['dveře','klika','výška','dosah']},
    {id:'int318-general-switch',cat:'obecne',status:'DOPORUČENÍ',title:'Výška vypínačů',recommended:'cca 900–1200 mm',minimum:'sjednotit v projektu',note:'Vol podle uživatelů; u přístupného návrhu ověř dosahové požadavky.',keywords:['vypínač','elektro','výška','dosah']},
    {id:'int318-general-socket',cat:'obecne',status:'DOPORUČENÍ',title:'Běžná výška zásuvek nad podlahou',recommended:'cca 250–350 mm',minimum:'podle účelu místnosti',note:'Kuchyně, koupelny, pracovní místa a přístupné stavby mají jiné provozní potřeby.',keywords:['zásuvka','elektro','výška']},
    {id:'int318-general-wall-art',cat:'obecne',status:'DOPORUČENÍ',title:'Výška středu obrazu / grafiky',recommended:'cca 1450–1550 mm',minimum:'přizpůsobit prostoru a pohledu',note:'V sedacích zónách nebo nad nábytkem může být střed níže.',keywords:['obraz','výška','interiér','stěna']},

    {id:'int318-law-room-height',cat:'obecne',status:'PŘEDPIS',title:'Světlá výška obytné / pobytové místnosti pro bydlení',recommended:'min. 2,5 m',minimum:'v podkroví min. 2,2 m',note:'Vyhláška č. 146/2024 Sb., § 38 odst. 1. Část plochy může být za podmínek vyhlášky snížena.',source:'Vyhláška č. 146/2024 Sb.',section:'§ 38 odst. 1',url:'https://www.zakonyprolidi.cz/cs/2024-146#p38',keywords:['předpis','světlá výška','obytná místnost','2,5 m']},
    {id:'int318-law-door',cat:'obecne',status:'PŘEDPIS',title:'Hlavní vstupní dveře do bytu a pobytové místnosti',recommended:'min. 800 mm světlá průchodná šířka',minimum:'800 mm',note:'Vyhláška č. 146/2024 Sb., § 39 odst. 1.',source:'Vyhláška č. 146/2024 Sb.',section:'§ 39 odst. 1',url:'https://www.zakonyprolidi.cz/cs/2024-146#p39',keywords:['předpis','dveře','šířka','800 mm']},
    {id:'int318-law-corridor-flat',cat:'obecne',status:'PŘEDPIS',title:'Chodba společných prostor bytového domu',recommended:'min. 1,2 m',minimum:'1,2 m',note:'Vyhláška č. 146/2024 Sb., § 39 odst. 3 písm. a).',source:'Vyhláška č. 146/2024 Sb.',section:'§ 39 odst. 3 písm. a)',url:'https://www.zakonyprolidi.cz/cs/2024-146#p39',keywords:['předpis','chodba','bytový dům','1,2 m']},
    {id:'int318-law-corridor-shop',cat:'retail',status:'PŘEDPIS',title:'Hlavní komunikace v prodejní místnosti',recommended:'2,0 m; v 1. NP 2,5 m',minimum:'dle podlaží',note:'Vyhláška č. 146/2024 Sb., § 39 odst. 3 písm. b).',source:'Vyhláška č. 146/2024 Sb.',section:'§ 39 odst. 3 písm. b)',url:'https://www.zakonyprolidi.cz/cs/2024-146#p39',keywords:['předpis','retail','obchod','komunikace']},
    {id:'int318-law-corridor-hotel',cat:'hotel',status:'PŘEDPIS',title:'Chodby ubytovacího zařízení nad 20 hostů',recommended:'hosté min. 1,5 m; zaměstnanci min. 1,2 m',minimum:'1,2 / 1,5 m',note:'Vyhláška č. 146/2024 Sb., § 39 odst. 3 písm. c).',source:'Vyhláška č. 146/2024 Sb.',section:'§ 39 odst. 3 písm. c)',url:'https://www.zakonyprolidi.cz/cs/2024-146#p39',keywords:['předpis','hotel','chodba','ubytování']},
    {id:'int318-law-corridor-kindergarten',cat:'skoly',status:'PŘEDPIS',title:'Chodba mateřské školy',recommended:'min. 1,2 m',minimum:'1,2 m',note:'Vyhláška č. 146/2024 Sb., § 39 odst. 3 písm. e), s výjimkami uvedenými ve vyhlášce.',source:'Vyhláška č. 146/2024 Sb.',section:'§ 39 odst. 3 písm. e)',url:'https://www.zakonyprolidi.cz/cs/2024-146#p39',keywords:['předpis','mateřská škola','chodba','1,2 m']},
    {id:'int318-law-ventilation',cat:'obecne',status:'PŘEDPIS',title:'Minimální větrání obytné místnosti',recommended:'0,5 h⁻¹ nebo 25 m³/h na osobu',minimum:'v době pobytu osob',note:'Vyhláška č. 146/2024 Sb. ve znění účinném od 1. 7. 2026, § 19 odst. 2.',source:'Vyhláška č. 146/2024 Sb.',section:'§ 19 odst. 2',url:'https://www.zakonyprolidi.cz/cs/2024-146#p19',keywords:['předpis','větrání','25 m3','obytná místnost']},
    {id:'int318-law-daylight',cat:'obecne',status:'PŘEDPIS',title:'Denní osvětlení obytného a pobytového prostoru',recommended:'plocha osvětlovacích otvorů min. 1/10 podlahové plochy',minimum:'1/10',note:'Vyhláška č. 146/2024 Sb. ve znění účinném od 1. 7. 2026, § 20 odst. 1.',source:'Vyhláška č. 146/2024 Sb.',section:'§ 20 odst. 1',url:'https://www.zakonyprolidi.cz/cs/2024-146#p20',keywords:['předpis','denní světlo','okno','1/10']},
    {id:'int318-law-social-single',cat:'hotel',status:'PŘEDPIS',title:'Jednolůžkový pokoj ve stavbě pro sociální služby',recommended:'min. 8 m²',minimum:'8 m²',note:'Vyhláška č. 146/2024 Sb., § 37 odst. 1 písm. a).',source:'Vyhláška č. 146/2024 Sb.',section:'§ 37 odst. 1 písm. a)',url:'https://www.zakonyprolidi.cz/cs/2024-146#p37',keywords:['předpis','sociální služby','pokoj','8 m2']},
    {id:'int318-law-social-double',cat:'hotel',status:'PŘEDPIS',title:'Dvoulůžkový pokoj ve stavbě pro sociální služby',recommended:'min. 14 m²',minimum:'14 m²',note:'Vyhláška č. 146/2024 Sb., § 37 odst. 1 písm. b).',source:'Vyhláška č. 146/2024 Sb.',section:'§ 37 odst. 1 písm. b)',url:'https://www.zakonyprolidi.cz/cs/2024-146#p37',keywords:['předpis','sociální služby','pokoj','14 m2']},
    {id:'int318-law-social-common',cat:'hotel',status:'PŘEDPIS',title:'Společný prostor ve stavbě pro sociální služby',recommended:'min. 18 m²',minimum:'18 m²',note:'Vyhláška č. 146/2024 Sb., § 37 odst. 2.',source:'Vyhláška č. 146/2024 Sb.',section:'§ 37 odst. 2',url:'https://www.zakonyprolidi.cz/cs/2024-146#p37',keywords:['předpis','sociální služby','společenská místnost','18 m2']}
  ];
  const ids=new Set(data.map(x=>x.id));
  for(const x of extra) if(!ids.has(x.id)){data.push(x);ids.add(x.id)}
  window.__TOOLBOX_INTERIOR_EXTRA_318_COUNT=extra.length;
})();