(()=>{
  const data=window.TOOLBOX_NORMS_V314Y;
  if(!Array.isArray(data)) return;

  const patch=(id,changes)=>{
    const x=data.find(i=>i.id===id);
    if(x) Object.assign(x,changes);
  };

  // Aktualizace podle konsolidovaného znění účinného od 1. 7. 2026.
  patch('law-stair-equal',{
    section:'§ 31 odst. 4',
    summary:'Všechny schodišťové stupně v jednom rameni hlavního schodiště musí mít stejnou návrhovou výšku; v přímých ramenech i stejnou návrhovou šířku.',
    url:'https://www.zakonyprolidi.cz/cs/2024-146#p31'
  });

  const extras=[
    {id:'law-floor-terrain',cat:'stavebni',type:'PRÁVNÍ PŘEDPIS',title:'Úroveň podlahy obytné místnosti nad terénem',value:'min. 0,15 m',source:'Vyhláška č. 146/2024 Sb., aktuální znění',section:'§ 18',summary:'Úroveň podlahy obytné místnosti musí být minimálně 0,15 m nad nejvyšší úrovní přilehlého upraveného terénu v rozhodném pásmu, pokud není místnost chráněna jiným způsobem.',keywords:['podlaha','terén','obytná místnost','0,15 m','vlhkost'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p18'},
    {id:'law-floor-groundwater',cat:'stavebni',type:'PRÁVNÍ PŘEDPIS',title:'Úroveň obytné místnosti nad podzemní vodou',value:'min. 0,5 m',source:'Vyhláška č. 146/2024 Sb., aktuální znění',section:'§ 18',summary:'Podlaha obytné místnosti má být minimálně 0,5 m nad hladinou podzemní vody, není-li prostor chráněn před nežádoucím působením vody jiným způsobem.',keywords:['podzemní voda','podlaha','hydroizolace','0,5 m'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p18'},
    {id:'law-ventilation-dwelling',cat:'interier',type:'PRÁVNÍ PŘEDPIS',title:'Minimální větrání obytné místnosti',value:'0,5 h⁻¹ nebo 25 m³/h/osoba',source:'Vyhláška č. 146/2024 Sb., ve znění č. 97/2026 Sb.',section:'§ 19 odst. 2',summary:'V době pobytu osob musí mít obytná místnost zajištěnu minimální intenzitu větrání 0,5 h⁻¹ nebo minimálně 25 m³/h venkovního vzduchu na osobu.',keywords:['větrání','vzduchotechnika','obytná místnost','25 m3','0,5 h-1'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p19'},
    {id:'law-daylight-openings',cat:'interier',type:'PRÁVNÍ PŘEDPIS',title:'Denní osvětlení obytného a pobytového prostoru',value:'otvory min. 1/10 podlahové plochy',source:'Vyhláška č. 146/2024 Sb., ve znění č. 97/2026 Sb.',section:'§ 20 odst. 1',summary:'Požadavek na denní osvětlení je splněn, pokud součet ploch osvětlovacích stavebních otvorů dosahuje alespoň jedné desetiny podlahové plochy osvětlovaného prostoru.',keywords:['denní osvětlení','okna','1/10','podlahová plocha','světlo'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p20'},
    {id:'law-shading-angle',cat:'urbanismus',type:'PRÁVNÍ PŘEDPIS',title:'Odstupový úhel stínění',value:'45°',source:'Vyhláška č. 146/2024 Sb., ve znění č. 97/2026 Sb.',section:'§ 20 odst. 4',summary:'Požadavky na zastínění jsou splněny dodržením odstupového úhlu stínění 45° od okna stávající obytné nebo pobytové místnosti podle přílohy vyhlášky.',keywords:['stínění','zastínění','45 stupňů','odstup','okno'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p20'},
    {id:'law-thermal-protection',cat:'stavebni',type:'PRÁVNÍ PŘEDPIS',title:'Tepelná ochrana budovy',value:'požadavek na tepelnou ochranu obálky',source:'Vyhláška č. 146/2024 Sb.',section:'§ 22 odst. 1',summary:'Budova musí být navržena s požadovanou tepelnou ochranou, vnitřní povrchovou teplotou, průvzdušností obálky, letní tepelnou stabilitou a ochranou proti vodě a vlhkosti.',keywords:['tepelná ochrana','obálka budovy','vlhkost','průvzdušnost','letní stabilita'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p22'},
    {id:'law-hazardous-floor',cat:'stavebni',type:'PRÁVNÍ PŘEDPIS',title:'Plochy pro manipulaci s látkami ohrožujícími půdu a vodu',value:'musí zabránit průniku do podloží',source:'Vyhláška č. 146/2024 Sb.',section:'§ 23',summary:'Podlahy a manipulační plochy v prostoru pravidelné manipulace s látkami ohrožujícími půdu nebo vodu musí být zajištěny proti jejich průniku do podloží.',keywords:['chemikálie','podlaha','voda','půda','nepropustnost'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p23'},
    {id:'law-outdoor-lighting',cat:'urbanismus',type:'PRÁVNÍ PŘEDPIS',title:'Omezení nežádoucích účinků venkovního osvětlení',value:'mj. reklamní zařízení nad 8 m²',source:'Vyhláška č. 146/2024 Sb.',section:'§ 24',summary:'U vybraných venkovních staveb a reklamních zařízení s celkovou plochou větší než 8 m² musí být omezeny nežádoucí účinky venkovního osvětlení; obdobně se posuzuje osvětlení fasád.',keywords:['osvětlení','světelné znečištění','reklama','fasáda','8 m2'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p24'},
    {id:'law-waste-place',cat:'projekt',type:'PRÁVNÍ PŘEDPIS',title:'Místo pro komunální odpad',value:'na pozemku stavby',source:'Vyhláška č. 146/2024 Sb.',section:'§ 25 odst. 1',summary:'Stavba musí být podle druhu a účelu vybavena místností nebo místem pro soustřeďování komunálního odpadu s kapacitou odpovídající účelu stavby.',keywords:['odpad','popelnice','kontejnery','odpadové hospodářství'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p25'},
    {id:'law-waste-shared-distance',cat:'urbanismus',type:'PRÁVNÍ PŘEDPIS',title:'Společné stanoviště komunálního odpadu',value:'do 300 m',source:'Vyhláška č. 146/2024 Sb.',section:'§ 25 odst. 2',summary:'Pro soubor staveb lze zřídit společné stanoviště pro soustřeďování komunálního odpadu ve vzdálenosti do 300 m.',keywords:['odpad','stanoviště','300 m','kontejnery','soubor staveb'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p25'},
    {id:'law-elevator-public',cat:'projekt',type:'PRÁVNÍ PŘEDPIS',title:'Výtah ve veřejných částech občanského vybavení',value:'přístup musí být zajištěn výtahem',source:'Vyhláška č. 146/2024 Sb.',section:'§ 32 odst. 2',summary:'U stavby občanského vybavení musí být do částí určených pro užívání veřejností zajištěn přístup výtahem.',keywords:['výtah','občanská vybavenost','veřejnost','přístupnost'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p32'},
    {id:'law-elevator-common-spaces',cat:'projekt',type:'PRÁVNÍ PŘEDPIS',title:'Výtah a společné prostory bytového domu',value:'přístup do všech společných prostor',source:'Vyhláška č. 146/2024 Sb.',section:'§ 32 odst. 4',summary:'Je-li v bytovém domě výtah, musí zajistit přístup do všech společných prostor domu.',keywords:['výtah','bytový dům','společné prostory','přístupnost'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p32'},
    {id:'law-waste-chute-opening',cat:'projekt',type:'PRÁVNÍ PŘEDPIS',title:'Spodní hrana vhozového otvoru shozu odpadu',value:'min. 1,1 m nad podlahou',source:'Vyhláška č. 146/2024 Sb.',section:'§ 33 odst. 4',summary:'Vhozový otvor shozové šachty nesmí být v obytné ani pobytové místnosti a jeho spodní hrana musí být nejméně 1,1 m nad podlahou nebo jinak zajištěna proti pádu.',keywords:['shoz odpadu','vhoz','1,1 m','odpad','bezpečnost'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p33'},
    {id:'law-fall-protection',cat:'stavebni',type:'PRÁVNÍ PŘEDPIS',title:'Ochrana proti pádu na okraji pochozí plochy',value:'zábradlí nebo jiná zábrana',source:'Vyhláška č. 146/2024 Sb.',section:'§ 34 odst. 1',summary:'Na okraji pochozí plochy, kde hrozí pád osob do hloubky, musí být zřízeno zábradlí nebo jiná zábrana s odpovídajícími parametry.',keywords:['zábradlí','pád','bezpečnost','hrana','pochozí plocha'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p34'},
    {id:'law-exterior-slip',cat:'stavebni',type:'PRÁVNÍ PŘEDPIS',title:'Protiskluz vnějších pochozích ploch',value:'bez zadržování vody; celoroční provoz',source:'Vyhláška č. 146/2024 Sb.',section:'§ 35 odst. 4',summary:'Vnější pochozí plochy, schodiště a rampy musí mít protiskluzovou úpravu řešenou tak, aby se na povrchu nezadržovala voda a byl možný celoroční provoz a údržba.',keywords:['protiskluz','dlažba','venkovní plocha','schodiště','rampa','voda'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p35'},
    {id:'law-social-room-single',cat:'interier',type:'PRÁVNÍ PŘEDPIS',title:'Jednolůžkový pokoj ve stavbě pro sociální služby',value:'min. 8 m²',source:'Vyhláška č. 146/2024 Sb.',section:'§ 37 odst. 1 písm. a)',summary:'Minimální plocha jednolůžkového pokoje ve stavbě pro sociální služby je 8 m².',keywords:['sociální služby','pokoj','8 m2','jednolůžkový'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p37'},
    {id:'law-social-room-double',cat:'interier',type:'PRÁVNÍ PŘEDPIS',title:'Dvoulůžkový pokoj ve stavbě pro sociální služby',value:'min. 14 m²',source:'Vyhláška č. 146/2024 Sb.',section:'§ 37 odst. 1 písm. b)',summary:'Minimální plocha dvoulůžkového pokoje ve stavbě pro sociální služby je 14 m².',keywords:['sociální služby','pokoj','14 m2','dvoulůžkový'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p37'},
    {id:'law-social-common-room',cat:'interier',type:'PRÁVNÍ PŘEDPIS',title:'Společný prostor ve stavbě pro sociální služby',value:'min. 18 m²',source:'Vyhláška č. 146/2024 Sb.',section:'§ 37 odst. 2',summary:'Minimální plocha prostoru pro společné setkávání ve stavbě pro sociální služby je 18 m².',keywords:['sociální služby','společenská místnost','18 m2','setkávání'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p37'},
    {id:'law-internal-transport',cat:'projekt',type:'PRÁVNÍ PŘEDPIS',title:'Průchod pro přepravu rozměrných předmětů',value:'1,95 × 0,75 × 0,8 m',source:'Vyhláška č. 146/2024 Sb., ve znění č. 97/2026 Sb.',section:'§ 39 odst. 2',summary:'Hlavní vnitřní komunikace budov s obytnými nebo pobytovými místnostmi musí umožnit přepravu předmětu délky 1,95 m, šířky 0,75 m a výšky 0,8 m; pro zdravotní a sociální péči platí větší profil.',keywords:['stěhování','chodba','průchod','1,95 m','0,75 m','vnitřní komunikace'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p39'},
    {id:'law-hotel-vestibule',cat:'interier',type:'PRÁVNÍ PŘEDPIS',title:'Předsíň pokoje hosta v ubytovacím zařízení',value:'min. 0,9 m',source:'Vyhláška č. 146/2024 Sb.',section:'§ 39 odst. 3 písm. d)',summary:'Nejmenší průchodná šířka předsíně pokoje hosta v ubytovacím zařízení je 0,9 m.',keywords:['hotel','ubytování','předsíň','0,9 m','pokoj hosta'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p39'},
    {id:'law-access-hole-ceiling',cat:'projekt',type:'PRÁVNÍ PŘEDPIS',title:'Průlezný otvor ve stropě',value:'min. 0,7 m',source:'Vyhláška č. 146/2024 Sb.',section:'§ 39 odst. 4',summary:'Průlezný otvor ve stropě nesmí mít žádný rozměr menší než 0,7 m.',keywords:['průlez','strop','otvor','0,7 m','revize'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p39'},
    {id:'law-access-hole-shaft',cat:'projekt',type:'PRÁVNÍ PŘEDPIS',title:'Vstupní otvor do šachty nebo kanálu',value:'min. 0,6 m',source:'Vyhláška č. 146/2024 Sb.',section:'§ 39 odst. 4',summary:'U vstupního otvoru do šachty nebo kanálu nesmí být žádný rozměr menší než 0,6 m; otvor nesmí být zužován žebříky nebo stupadly.',keywords:['šachta','kanál','revize','otvor','0,6 m'],url:'https://www.zakonyprolidi.cz/cs/2024-146#p39'},
    {id:'law-flat-bath-wc',cat:'interier',type:'PRÁVNÍ PŘEDPIS',title:'Minimální hygienické vybavení bytu',value:'min. 1 WC + 1 koupelna',source:'Vyhláška č. 146/2024 Sb.',section:'Příloha č. 3 bod 1',summary:'Byt musí být vybaven minimálně jednou záchodovou mísou a jednou koupelnou.',keywords:['byt','koupelna','wc','záchod','hygiena'],url:'https://www.zakonyprolidi.cz/cs/2024-146'},
    {id:'law-public-wc-cultural',cat:'interier',type:'PRÁVNÍ PŘEDPIS',title:'Hygienické zařízení pro veřejnost – kulturní a sportovní stavby',value:'1 WC / 50 žen; 1 WC / 100 mužů',source:'Vyhláška č. 146/2024 Sb.',section:'Příloha č. 3 bod 2.1',summary:'U kulturních, sportovních a obdobných staveb pro veřejnost se vyžaduje samostatné hygienické zařízení; základní poměr je 1 záchodová mísa na 50 žen nebo 100 mužů a dále pisoár na každých 50 mužů.',keywords:['wc','toalety','veřejnost','sport','kultura','hygiena'],url:'https://www.zakonyprolidi.cz/cs/2024-146'}
  ];

  const ids=new Set(data.map(x=>x.id));
  extras.forEach(x=>{if(!ids.has(x.id)){data.push(x);ids.add(x.id)}});
})();
