(()=>{
  const HANDLE_PREFIX='presentationSourceHandle:';
  const runtimeHandles=new Map();
  let sourceCounter=0;

  function pageNo(){return Number((typeof currentPreviewPage!=='undefined'&&currentPreviewPage)||1)}
  function projectKey(){return (typeof currentProjectName!=='undefined'&&currentProjectName)||'default'}
  function handleKey(){return `${projectKey()}:${Date.now()}:${++sourceCounter}`}
  async function storeHandle(key,handle){if(!key||!handle)return;runtimeHandles.set(key,handle);try{if(typeof idbSet==='function')await idbSet(HANDLE_PREFIX+key,handle)}catch(e){console.warn('Uložení odkazu na zdroj',e)}}
  async function loadHandle(key){if(!key)return null;if(runtimeHandles.has(key))return runtimeHandles.get(key);try{if(typeof idbGet==='function'){const h=await idbGet(HANDLE_PREFIX+key);if(h){runtimeHandles.set(key,h);return h}}}catch(e){console.warn(e)}return null}
  async function fileFromHandle(key,request=false){const h=await loadHandle(key);if(!h)return null;try{let p=await h.queryPermission?.({mode:'read'});if(p!=='granted'&&request)p=await h.requestPermission?.({mode:'read'});if(p==='denied')return null;return await h.getFile()}catch(e){console.warn('Zdroj není dostupný',e);return null}}
  function dataUrl(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
  async function pickHandle(kind='any'){
    if(!window.showOpenFilePicker)return null;
    const types=kind==='pdf'?[{description:'PDF',accept:{'application/pdf':['.pdf']}}]:kind==='image'?[{description:'Obrázek',accept:{'image/png':['.png'],'image/jpeg':['.jpg','.jpeg'],'image/webp':['.webp']}}]:[{description:'PDF nebo obrázek',accept:{'application/pdf':['.pdf'],'image/png':['.png'],'image/jpeg':['.jpg','.jpeg'],'image/webp':['.webp']}}];
    try{const [h]=await showOpenFilePicker({multiple:false,types});return h||null}catch(e){if(e?.name!=='AbortError')console.warn(e);return null}
  }
  function isPdf(f){return f?.type==='application/pdf'||/\.pdf$/i.test(f?.name||'')}

  function css(){if(document.getElementById('presentation-source-crop-v333-style'))return;const s=document.createElement('style');s.id='presentation-source-crop-v333-style';s.textContent=`
    .pm-mini-tools{position:absolute;left:-1px;top:-29px;z-index:60;display:none;align-items:center;gap:3px;background:#fff;border:1px solid #d4d4d8;border-radius:6px;padding:3px;box-shadow:0 2px 8px rgba(0,0,0,.13);white-space:nowrap}
    .presentation-media-item.selected .pm-mini-tools{display:flex}.pm-mini-tools button,.mb-mini-tools button{width:24px;height:24px;padding:0;border:1px solid #d4d4d8;border-radius:4px;background:#fff;cursor:pointer;font-size:13px}.pm-mini-tools button:hover,.mb-mini-tools button:hover{background:#f7f197;border-color:#18181b}
    .pm-crop-edit,.mb-crop-edit{position:absolute;inset:0;z-index:55;cursor:crosshair;background:rgba(247,241,151,.12)}
    .pm-crop-edit svg,.mb-crop-edit svg,.mb-crop-mask{width:100%;height:100%;display:block;position:absolute;inset:0;overflow:visible;pointer-events:none}
    .pm-crop-confirm,.mb-crop-confirm{position:absolute;left:5px;bottom:5px;z-index:65;display:flex;gap:4px}.pm-crop-confirm button,.mb-crop-confirm button{min-width:30px;height:27px;border:1px solid #18181b;border-radius:5px;background:#fff;cursor:pointer}.pm-crop-confirm .ok,.mb-crop-confirm .ok{background:#f7f197}
    .mb-mini-tools{position:absolute;left:4px;top:4px;z-index:20;display:none;gap:3px}.moodboard-cell:hover .mb-mini-tools,.moodboard-cell.mb-selected .mb-mini-tools{display:flex}
    .moodboard-cell .cell-delete{z-index:22!important}.mb-source-badge{position:absolute;left:4px;bottom:4px;z-index:19;background:rgba(255,255,255,.86);border-radius:4px;padding:2px 5px;font-size:8px;color:#52525b;display:none}.moodboard-cell:hover .mb-source-badge{display:block}
  `;document.head.appendChild(s)}

  async function renderPdfPreview(file,page,target=1800){if(!window.pdfjsLib)return null;const bytes=new Uint8Array(await file.arrayBuffer()),pdf=await pdfjsLib.getDocument({data:bytes}).promise;if(page>pdf.numPages)throw new Error(`Zdrojové PDF má jen ${pdf.numPages} stran.`);const p=await pdf.getPage(page),v0=p.getViewport({scale:1}),sc=Math.max(1,Math.min(4,target/v0.width)),v=p.getViewport({scale:sc}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;return{preview:c.toDataURL('image/png'),aspect:v0.width/v0.height,sourceData:await dataUrl(file)}}

  async function refreshMediaObject(o,request=true){
    const f=await fileFromHandle(o.sourceHandleKey,request);if(!f)return false;
    if(o.kind==='pdf'){
      const r=await renderPdfPreview(f,o.sourcePage||1);o.dataUrl=r.preview;o.sourceData=r.sourceData;o.sourceName=f.name;o.aspect=r.aspect;
    }else{
      const d=await dataUrl(f),info=await new Promise((res,rej)=>{const im=new Image();im.onload=()=>res({aspect:im.naturalWidth/Math.max(1,im.naturalHeight)});im.onerror=rej;im.src=d});o.dataUrl=d;o.sourceName=f.name;o.aspect=info.aspect;
    }
    return true;
  }
  async function relinkMedia(o){const h=await pickHandle(o.kind==='pdf'?'pdf':'image');if(!h)return false;const k=handleKey();await storeHandle(k,h);o.sourceHandleKey=k;o.sourceRef=null;o.sourceData=null;const ok=await refreshMediaObject(o,true);if(ok){await saveProject();window.presentationMediaState&&renderMediaDecorationsSoon()}return ok}

  function mediaObjFromEl(el){const st=window.presentationMediaState,list=st?.byPage?.[pageNo()]||[];return list.find(x=>x.id===el.dataset.id)}
  function cropPolygonCss(points){return points?.length>=3?`polygon(${points.map(p=>`${(p.x*100).toFixed(2)}% ${(p.y*100).toFixed(2)}%`).join(',')})`:''}
  function applyMediaCrop(el,o){const img=el.querySelector('img');if(!img)return;img.style.clipPath=cropPolygonCss(o.cropPoints)||''}
  function decorateMedia(){document.querySelectorAll('.presentation-media-item').forEach(el=>{const o=mediaObjFromEl(el);if(!o)return;applyMediaCrop(el,o);if(el.querySelector('.pm-mini-tools'))return;const tools=document.createElement('div');tools.className='pm-mini-tools';tools.innerHTML='<button title="Znovu načíst ze zdroje">↻</button><button title="Znovu propojit zdroj">🔗</button><button title="Ořez / maska">✂</button>';const [reload,relink,crop]=tools.querySelectorAll('button');reload.onclick=async e=>{e.stopPropagation();if(!o.sourceHandleKey){await relinkMedia(o);return}if(!(await refreshMediaObject(o,true))){alert('Původní zdroj není dostupný. Použij tlačítko Propojit.');return}applyMediaCrop(el,o);el.querySelector('img').src=o.dataUrl;await saveProject()};relink.onclick=async e=>{e.stopPropagation();await relinkMedia(o);el.querySelector('img').src=o.dataUrl;applyMediaCrop(el,o)};crop.onclick=e=>{e.stopPropagation();startCrop(el,o,false)};el.appendChild(tools)})}

  function startCrop(host,obj,isMood){
    host.querySelector(isMood?'.mb-crop-edit':'.pm-crop-edit')?.remove();const old=(obj.cropPoints||[]).map(p=>({...p})),pts=old.length?old.map(p=>({...p})):[];const layer=document.createElement('div');layer.className=isMood?'mb-crop-edit':'pm-crop-edit';layer.innerHTML=`<svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline fill="rgba(247,241,151,.20)" stroke="#18181b" stroke-width=".7" vector-effect="non-scaling-stroke"></polyline></svg><div class="${isMood?'mb-crop-confirm':'pm-crop-confirm'}"><button class="ok" title="Potvrdit">✓</button><button class="cancel" title="Zrušit">×</button><button class="reset" title="Zrušit ořez">↺</button></div>`;host.appendChild(layer);const poly=layer.querySelector('polyline');const redraw=()=>poly.setAttribute('points',pts.map(p=>`${p.x*100},${p.y*100}`).join(' '));redraw();layer.onpointerdown=e=>{if(e.target.closest('button'))return;e.stopPropagation();const r=layer.getBoundingClientRect();pts.push({x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))});redraw()};layer.querySelector('.ok').onclick=async e=>{e.stopPropagation();if(pts.length&&pts.length<3){alert('Pro libovolný ořez označ alespoň 3 body.');return}obj.cropPoints=pts.length>=3?pts:null;layer.remove();isMood?applyMoodCrop(host,obj):applyMediaCrop(host,obj);await saveProject()};layer.querySelector('.cancel').onclick=e=>{e.stopPropagation();obj.cropPoints=old.length?old:null;layer.remove()};layer.querySelector('.reset').onclick=async e=>{e.stopPropagation();obj.cropPoints=null;layer.remove();isMood?applyMoodCrop(host,obj):applyMediaCrop(host,obj);await saveProject()}
  }

  function moodCell(el){const p=Number(el.dataset.page||pageNo()),i=Number(el.dataset.cellIndex);return{p,i,cell:(typeof allPagesTexts!=='undefined'&&allPagesTexts[p]?.cells?.[i])||null}}
  function applyMoodCrop(el,cell){el.querySelector('.mb-crop-mask')?.remove();if(!cell?.cropPoints?.length)return;const pts=cell.cropPoints.map(p=>`${p.x*100},${p.y*100}`).join(' '),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('class','mb-crop-mask');svg.setAttribute('viewBox','0 0 100 100');svg.innerHTML=`<defs><mask id="m_${Math.random().toString(36).slice(2)}"><rect width="100" height="100" fill="white"/><polygon points="${pts}" fill="black"/></mask></defs><path d="M0 0H100V100H0Z M${cell.cropPoints.map(p=>`${p.x*100} ${p.y*100}`).join(' L')} Z" fill="rgba(255,255,255,.94)" fill-rule="evenodd"/>`;el.appendChild(svg)}
  async function setMoodSource(el,cell,handle){const key=handleKey();await storeHandle(key,handle);cell.sourceHandleKey=key;cell.sourceName=(await handle.getFile()).name;const f=await fileFromHandle(key,true),d=await dataUrl(f);cell.imageData=d;cell.imageRef=null;cell._sourceHydrated=true;if(typeof updateCellImageTransform==='function')updateCellImageTransform(Number(el.dataset.page),Number(el.dataset.cellIndex));const img=el.querySelector('.cell-img');if(img)img.src=d;await saveProject()}
  async function reloadMood(el,cell,request=true){const f=await fileFromHandle(cell.sourceHandleKey,request);if(!f)return false;const d=await dataUrl(f);cell.imageData=d;cell.sourceName=f.name;cell._sourceHydrated=true;const img=el.querySelector('.cell-img');if(img)img.src=d;if(typeof updateCellImageTransform==='function')updateCellImageTransform(Number(el.dataset.page),Number(el.dataset.cellIndex));return true}
  function decorateMood(){document.querySelectorAll('.moodboard-cell').forEach(el=>{const {cell}=moodCell(el);if(!cell)return;applyMoodCrop(el,cell);if(cell.sourceHandleKey&&!cell._sourceHydrated){cell._sourceHydrated=true;reloadMood(el,cell,false).then(ok=>{if(ok)saveProject()})}if(el.querySelector('.mb-mini-tools'))return;const t=document.createElement('div');t.className='mb-mini-tools';t.innerHTML='<button title="Znovu načíst ze zdroje">↻</button><button title="Znovu propojit zdroj">🔗</button><button title="Ořez / maska">✂</button>';const b=document.createElement('span');b.className='mb-source-badge';b.textContent=cell.sourceName||'zdroj v projektu';el.append(t,b);const [reload,relink,crop]=t.querySelectorAll('button');reload.onclick=async e=>{e.stopPropagation();if(!cell.sourceHandleKey){const h=await pickHandle('image');if(h)await setMoodSource(el,cell,h);return}if(!(await reloadMood(el,cell,true)))alert('Původní zdroj není dostupný. Použij Propojit.');else await saveProject()};relink.onclick=async e=>{e.stopPropagation();const h=await pickHandle('image');if(h)await setMoodSource(el,cell,h)};crop.onclick=e=>{e.stopPropagation();startCrop(el,cell,true)}})}

  async function interceptNewMedia(e){const btn=e.target.closest?.('#presentation-media-add-btn');if(!btn||!window.showOpenFilePicker)return;e.preventDefault();e.stopImmediatePropagation();const h=await pickHandle('any');if(!h)return;const f=await h.getFile(),st=window.presentationMediaState,p=pageNo(),before=new Set((st?.byPage?.[p]||[]).map(x=>x.id)),key=handleKey();await storeHandle(key,h);const input=document.getElementById('presentation-media-input');if(!input)return;const dt=new DataTransfer();dt.items.add(f);input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));let tries=0;const timer=setInterval(async()=>{tries++;const list=window.presentationMediaState?.byPage?.[p]||[],o=list.find(x=>!before.has(x.id));if(o){clearInterval(timer);o.sourceHandleKey=key;o.sourceName=f.name;o.sourceRef=null;o.sourceData=null;await saveProject();decorateMedia()}else if(tries>1200)clearInterval(timer)},100)}
  async function interceptMoodPlus(e){const plus=e.target.closest?.('.moodboard-cell .cell-plus');if(!plus||!window.showOpenFilePicker)return;e.preventDefault();e.stopImmediatePropagation();const el=plus.closest('.moodboard-cell'),{p,i,cell}=moodCell(el);if(!cell)return;const h=await pickHandle('image');if(!h)return;const f=await h.getFile(),d=await dataUrl(f);if(typeof addImageToCell==='function')await addImageToCell(p,i,d,f.name);const c=(typeof allPagesTexts!=='undefined'&&allPagesTexts[p]?.cells?.[i])||cell;await setMoodSource(el,c,h);setTimeout(decorateMood,0)}

  async function preExportRefresh(){const st=window.presentationMediaState;for(const list of Object.values(st?.byPage||{}))for(const o of list||[]){if(!o.sourceHandleKey)continue;const ok=await refreshMediaObject(o,true);if(!ok&&o.kind==='pdf')throw new Error(`Zdroj PDF „${o.sourceName||o.name}“ není dostupný. Použij u prvku tlačítko Propojit.`)}for(const [p,d] of Object.entries(typeof allPagesTexts!=='undefined'?allPagesTexts:{})){if(!d?.cells)continue;for(const c of d.cells){if(c.sourceHandleKey)await reloadMood(document.querySelector(`.moodboard-cell[data-page="${p}"][data-cell-index="${d.cells.indexOf(c)}"]`)||document.createElement('div'),c,true)}}}
  function wrapRun(){const fn=window.runPanel;if(typeof fn!=='function'||fn.__v333Sources)return;const w=async function(){try{await preExportRefresh()}catch(e){alert(e.message||e);return}return fn.apply(this,arguments)};w.__v333Sources=true;window.runPanel=w}
  async function saveProject(){try{scheduleAutosave?.();await persistProjectStructureNow?.()}catch(e){console.warn('Uložení zdroje/cropu',e)}}
  function renderMediaDecorationsSoon(){setTimeout(()=>{decorateMedia();decorateMood()},0)}

  function init(){css();document.addEventListener('click',interceptNewMedia,true);document.addEventListener('click',interceptMoodPlus,true);const obs=new MutationObserver(()=>{decorateMedia();decorateMood();wrapRun()});obs.observe(document.documentElement,{childList:true,subtree:true});decorateMedia();decorateMood();wrapRun();setInterval(wrapRun,1000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
