(()=>{
  const PROJECTS_STORE='toolbox.pricingOffer.projects.v346';
  const ACTIVE_STORE='toolbox.pricingOffer.active.v346';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0}).format(Number(n)||0);
  function loadState(){try{const ps=JSON.parse(localStorage.getItem(PROJECTS_STORE)||'[]')||[];const id=localStorage.getItem(ACTIVE_STORE);return ps.find(p=>p.id===id)?.data||null}catch(_){return null}}
  const rowRate=(g,it)=>{const r=Number(it?.rateOverride);return Number.isFinite(r)&&r>=0?r:(Number(g?.rate)||0)};
  const itemTotal=(g,it)=>it.on===false?0:(g.mode==='hours'?(Number(it.qty)||0)*rowRate(g,it):(Number(it.price)||0));
  const groupTotal=g=>(g.items||[]).reduce((s,it)=>s+itemTotal(g,it),0);
  const groupHours=g=>g.mode==='hours'?(g.items||[]).reduce((s,it)=>s+(it.on===false?0:Number(it.qty)||0),0):0;
  function summary(s){const groups=s?.groups||[];const arch=groups.filter(g=>g.mode==='hours').reduce((a,g)=>a+groupTotal(g),0);const prof=groups.filter(g=>g.mode==='fixed').reduce((a,g)=>a+groupTotal(g),0);const hours=groups.reduce((a,g)=>a+groupHours(g),0);const net=arch+prof,vat=net*(Number(s?.vat)||0)/100;return {arch,prof,hours,net,vat,gross:net+vat}}
  function exportOffer(){
    const state=loadState();if(!state)return alert('Nejdřív otevři cenovou nabídku.');
    const s=summary(state),groups=(state.groups||[]).filter(g=>(g.items||[]).some(i=>i.on!==false));
    const allRates=[];groups.filter(g=>g.mode==='hours').forEach(g=>(g.items||[]).filter(i=>i.on!==false).forEach(it=>{const r=rowRate(g,it);if(r>0)allRates.push(r)}));
    const rateSet=[...new Set(allRates)];const rateText=rateSet.length===1?`${money(rateSet[0]).replace(/Kč\s?$/,'')} Kč/h`:rateSet.length>1?'individuálně dle položek':'—';
    let sections='';
    groups.forEach((g,gi)=>{
      const items=(g.items||[]).filter(i=>i.on!==false);const fixed=g.mode==='fixed';
      sections+=`<section class="offer-section"><div class="section-title"><span>${String(gi+1).padStart(2,'0')}</span><span>${esc((g.name||'').toUpperCase())}</span></div><div class="thead ${fixed?'fixed':''}"><span>Č.</span><span>${fixed?'Profese':'Pracovní balíček'}</span><span>Rozsah služby</span>${fixed?'':`<span>Hodiny</span><span>Sazba Kč/h</span>`}<span>Cena bez DPH</span></div>`;
      items.forEach((it,ii)=>{const r=rowRate(g,it);sections+=`<div class="tr ${fixed?'fixed':''}"><span>${String(gi+1).padStart(2,'0')}.${ii+1}</span><span>${esc(it.name||'')}</span><span>${esc(it.description||'')}</span>${fixed?'':`<span class="num">${Number(it.qty)||0} h</span><span class="num">${money(r).replace(/Kč\s?$/,'')} Kč/h</span>`}<b>${money(itemTotal(g,it))}</b></div>`});
      sections+=`<div class="subtotal ${fixed?'fixed':''}"><span>${esc((g.name||'').toUpperCase())} CELKEM</span>${fixed?'':`<span>${groupHours(g)} h</span>`}<b>${money(groupTotal(g))}</b></div></section>`;
    });
    const fontBook=new URL('font/Dunwich Type Founders - Antarctican Mono Book.otf',window.location.href).href;
    const fontBold=new URL('font/Dunwich Type Founders - Antarctican Mono Bold.otf',window.location.href).href;
    const w=window.open('','_blank');if(!w){alert('Povol vyskakovací okna pro Tisk / PDF.');return}
    w.document.write(`<!doctype html><html><head><meta charset="utf-8"><base href="${esc(window.location.href)}"><title>Cenová nabídka – ${esc(state.project||'Projekt')}</title><style>
      @font-face{font-family:'Antarctican Mono';src:url('${fontBook}') format('opentype');font-weight:400;font-style:normal;font-display:block}
      @font-face{font-family:'Antarctican Mono';src:url('${fontBold}') format('opentype');font-weight:700;font-style:normal;font-display:block}
      @page{size:A4 portrait;margin:10mm 10mm 9mm}
      *{box-sizing:border-box}html,body{margin:0;padding:0;background:#fff;color:#171717}body{font-family:'Antarctican Mono',monospace;font-size:7.4pt;line-height:1.32;-webkit-print-color-adjust:exact;print-color-adjust:exact}.page{width:100%;max-width:190mm;margin:0 auto}.brand-top{font-weight:700;font-size:7.2pt;margin:1mm 0 7mm}.title{font-size:15.4pt;font-weight:400;letter-spacing:.01em;margin:0 0 1.1mm}.subtitle{font-size:7.2pt;color:#6b6b6b;letter-spacing:.04em;margin-bottom:3.8mm;text-transform:uppercase}.two-col-head{display:grid;grid-template-columns:1fr 1fr;gap:0}.yellow{background:#f4ee73;padding:1.7mm 1.4mm;font-size:7.1pt}.info-wrap{display:grid;grid-template-columns:1fr 1fr;margin-bottom:3.5mm}.info-box{display:grid;grid-template-columns:25mm 1fr;row-gap:1.15mm;padding:2.1mm 1.4mm 1.4mm;font-size:6.8pt}.info-box.right{grid-template-columns:1fr 31mm}.info-box.right span:nth-child(odd){color:#777}.info-box.right b{text-align:right}.info-box span:nth-child(odd){color:#777}.info-box b{font-weight:400}.offer-section{margin-top:2.2mm;break-inside:auto}.section-title{display:grid;grid-template-columns:7mm 1fr;background:#f4ee73;padding:1.55mm 1.2mm;font-size:7.4pt}.thead,.tr{display:grid;grid-template-columns:15mm 46mm 1fr 14mm 20mm 23mm}.thead.fixed,.tr.fixed{grid-template-columns:15mm 46mm 1fr 23mm}.thead{background:#202023;color:#fff;font-size:6.5pt}.thead span{padding:1.7mm 1.2mm}.tr{min-height:10.5mm;align-items:center;break-inside:avoid}.tr span,.tr b{padding:1.65mm 1.2mm}.tr b{text-align:right;font-weight:400}.tr .num{text-align:right;white-space:nowrap}.subtotal{display:grid;grid-template-columns:1fr 18mm 23mm;background:#efefed;margin-top:.4mm;padding:1.55mm 1.2mm;font-size:6.7pt;break-inside:avoid}.subtotal.fixed{grid-template-columns:1fr 23mm}.subtotal span:nth-last-child(2),.subtotal b{text-align:right}.subtotal b{font-weight:400}.recap{margin-top:2.4mm;break-inside:avoid}.recap-head{background:#f4ee73;padding:1.6mm 1.2mm;font-size:7.2pt}.recap-row{display:grid;grid-template-columns:1fr 30mm;padding:.75mm 1.2mm;font-size:7pt}.recap-row b{text-align:right;font-weight:400}.recap-row.strong{background:#efefed}.recap-row.vat{grid-template-columns:1fr 15mm 30mm}.recap-row.vat span:nth-child(2),.recap-row.vat b{text-align:right}.recap-row.total{background:#f4ee73;font-size:10.6pt;padding:1.9mm 1.2mm;margin-top:.6mm}.note{margin:3.2mm 0 4.5mm;font-size:6.4pt;line-height:1.42}.footer{height:4.7mm;background:#f4ee73;display:flex;align-items:center;justify-content:flex-end;padding:0 1.2mm;font-weight:700;font-size:6.7pt}@media print{.offer-section,.recap,.tr,.subtotal{page-break-inside:avoid}}
    </style></head><body><div class="page"><div class="brand-top">20-20-ARCHITEKTI</div><div class="title">CENOVÁ NABÍDKA – PROJEKT INTERIÉRU</div><div class="subtitle">${esc((state.project||'').toUpperCase())}</div><div class="two-col-head"><div class="yellow">ÚDAJE NABÍDKY</div><div class="yellow">KLÍČOVÉ VSTUPY A VÝSTUPY</div></div><div class="info-wrap"><div class="info-box"><span>Projekt</span><b>${esc(state.project||'—')}</b><span>Objednatel</span><b>${esc(state.client||'—')}</b><span>Datum</span><b>${esc(state.date?new Date(state.date+'T12:00:00').toLocaleDateString('cs-CZ'):'—')}</b></div><div class="info-box right"><span>Hodinová sazba bez DPH</span><b>${rateText}</b><span>Celkový rozsah arch. prací</span><b>${s.hours} h</b><span>Cena arch. prací bez DPH</span><b>${money(s.arch)}</b><span>Profesní subdodávky bez DPH</span><b>${money(s.prof)}</b><span>Cena projektu celkem bez DPH</span><b>${money(s.net)}</b></div></div>${sections}<div class="recap"><div class="recap-head">REKAPITULACE CENY</div><div class="recap-row"><span>Architektonické práce</span><b>${money(s.arch)}</b></div><div class="recap-row"><span>Profesní subdodávky</span><b>${money(s.prof)}</b></div><div class="recap-row strong"><span>CENA CELKEM BEZ DPH</span><b>${money(s.net)}</b></div><div class="recap-row vat"><span>DPH</span><span>${Number(state.vat)||0}%</span><b>${money(s.vat)}</b></div><div class="recap-row total"><span>CENA CELKEM VČETNĚ DPH</span><b>${money(s.gross)}</b></div></div>${state.note?`<div class="note">${esc(state.note)}</div>`:''}<div class="footer">20-20-ARCHITEKTI</div></div><script>window.onload=async()=>{try{await document.fonts.load("400 12px 'Antarctican Mono'");await document.fonts.load("700 12px 'Antarctican Mono'");await document.fonts.ready}catch(e){}setTimeout(()=>window.print(),300)}<\/script></body></html>`);w.document.close();
  }
  function bind(){const root=document.getElementById('tool-pricing');if(!root)return;const b=root.querySelector('#pr-print');if(!b||b.dataset.v351)return;b.dataset.v351='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();exportOffer()},{capture:true})}
  function init(){bind();const root=document.getElementById('tool-pricing');if(root)new MutationObserver(()=>requestAnimationFrame(bind)).observe(root,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();