(()=>{
  const PROJECTS_STORE='toolbox.pricingOffer.projects.v346';
  const ACTIVE_STORE='toolbox.pricingOffer.active.v346';
  const STYLE_ID='pricing-estimate-v347-style';
  const STOP=new Set(['a','i','v','ve','na','do','z','ze','s','se','pro','po','u','k','ke','od','za','při','pri','dle','bez','nebo','the']);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0}).format(Number(n)||0);
  function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
  function tokens(s){return new Set(norm(s).split(/\s+/).filter(x=>x.length>2&&!STOP.has(x)))}
  function similarity(a,b){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let hit=0;A.forEach(x=>{if(B.has(x))hit++});return hit/Math.max(A.size,B.size)}
  function median(arr){const a=arr.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return 0;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
  function roundHours(n){if(!Number.isFinite(n)||n<=0)return 1;if(n<=8)return Math.max(1,Math.round(n));if(n<=24)return Math.round(n/2)*2;return Math.round(n/5)*5}
  function loadProjects(){try{return JSON.parse(localStorage.getItem(PROJECTS_STORE)||'[]')||[]}catch(_){return[]}}
  function activeProject(){const id=localStorage.getItem(ACTIVE_STORE);return loadProjects().find(p=>p.id===id)||null}
  function findTarget(project,gid,iid){const g=project?.data?.groups?.find(x=>String(x.id)===String(gid));const it=g?.items?.find(x=>String(x.id)===String(iid));return g&&it?{g,it}:null}
  function collectRefs(projects,targetG,targetIt){const refs=[];for(const p of projects){for(const g of p?.data?.groups||[]){for(const it of g.items||[]){if(String(it.id)===String(targetIt.id)&&String(g.id)===String(targetG.id)&&p.id===localStorage.getItem(ACTIVE_STORE))continue;if(it.on===false)continue;if(g.mode==='hours'){const qty=Number(it.qty),rate=Number(g.rate);if(qty>0&&rate>0)refs.push({mode:'hours',name:it.name||'',group:g.name||'',qty,rate,price:qty*rate})}else{const price=Number(it.price);if(price>0)refs.push({mode:'fixed',name:it.name||'',group:g.name||'',price})}}}return refs}
  function estimateHours(projects,g,it){const refs=collectRefs(projects,g,it).filter(r=>r.mode==='hours');if(!refs.length)return null;const scored=refs.map(r=>{const sim=similarity(it.name,r.name);const sameGroup=norm(g.name)===norm(r.group);const exact=norm(it.name)&&norm(it.name)===norm(r.name);let w=1+sim*5+(sameGroup?2:0)+(exact?8:0);return {...r,sim,sameGroup,exact,w}}).sort((a,b)=>b.w-a.w);const useful=scored.filter(x=>x.exact||x.sim>=.18||x.sameGroup).slice(0,8);const pool=useful.length?useful:scored.slice(0,8);let num=0,den=0;pool.forEach(x=>{num+=x.qty*x.w;den+=x.w});let hours=den?num/den:median(refs.map(x=>x.qty));hours=roundHours(hours);const rate=Number(g.rate)||Math.round(median(refs.map(x=>x.rate))/50)*50||0;const confidence=pool.some(x=>x.exact)?'vysoká':pool.some(x=>x.sim>=.3)?'střední':pool.filter(x=>x.sameGroup).length>=2?'střední':'orientační';return {hours,rate,cost:hours*rate,confidence,refs:pool.length}}
  function estimateFixed(projects,g,it){const refs=collectRefs(projects,g,it).filter(r=>r.mode==='fixed');if(!refs.length)return null;const scored=refs.map(r=>{const sim=similarity(it.name,r.name);const sameGroup=norm(g.name)===norm(r.group);const exact=norm(it.name)&&norm(it.name)===norm(r.name);let w=1+sim*5+(sameGroup?2:0)+(exact?8:0);return {...r,sim,sameGroup,exact,w}}).sort((a,b)=>b.w-a.w);const useful=scored.filter(x=>x.exact||x.sim>=.18||x.sameGroup).slice(0,8);const pool=useful.length?useful:scored.slice(0,8);let num=0,den=0;pool.forEach(x=>{num+=x.price*x.w;den+=x.w});let price=den?num/den:median(refs.map(x=>x.price));price=Math.max(1000,Math.round(price/1000)*1000);const confidence=pool.some(x=>x.exact)?'vysoká':pool.some(x=>x.sim>=.3)?'střední':pool.filter(x=>x.sameGroup).length>=2?'střední':'orientační';return {price,confidence,refs:pool.length}}
  function toast(html){let t=document.getElementById('pricing-estimate-toast');if(!t){t=document.createElement('div');t.id='pricing-estimate-toast';document.body.appendChild(t)}t.innerHTML=html;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),4200)}
  function estimateRow(row){const sec=row.closest('.pricing-group');if(!sec)return;const p=activeProject();if(!p)return toast('Nejdřív otevři uložený projekt cenové nabídky.');const target=findTarget(p,sec.dataset.g,row.dataset.i);if(!target)return;const projects=loadProjects();if(target.g.mode==='hours'){const e=estimateHours(projects,target.g,target.it);if(!e)return toast('Zatím není dost údajů pro odhad hodin.');const input=row.querySelector('.pr-qty');if(input){input.value=e.hours;input.dispatchEvent(new Event('change',{bubbles:true}))}toast(`<b>Odhad: ${e.hours} h</b> × ${money(e.rate)} = <b>${money(e.cost)}</b><small>Spolehlivost: ${esc(e.confidence)} · použito ${e.refs} srovnatelných položek</small>`)}else{const e=estimateFixed(projects,target.g,target.it);if(!e)return toast('Zatím není dost údajů pro odhad ceny.');const input=row.querySelector('.pr-price');if(input){input.value=e.price;input.dispatchEvent(new Event('change',{bubbles:true}))}toast(`<b>Odhad: ${money(e.price)}</b><small>Spolehlivost: ${esc(e.confidence)} · použito ${e.refs} srovnatelných položek</small>`)}}
  function injectStyle(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
    #tool-pricing .pricing-row{grid-template-columns:26px minmax(230px,1fr) 100px 120px 66px 34px!important}
    #tool-pricing .pr-estimate{border:1px solid #d4cc5d;background:#fffef3;border-radius:6px;padding:6px 7px;font-size:9px;cursor:pointer;white-space:nowrap;color:#27272a}
    #tool-pricing .pr-estimate:hover{background:#f7f197;border-color:#a8a24b}
    #pricing-estimate-toast{position:fixed;right:22px;bottom:22px;z-index:2147482000;max-width:380px;background:#18181b;color:#fff;border-radius:10px;padding:11px 14px;box-shadow:0 10px 30px rgba(0,0,0,.22);font-size:12px;line-height:1.4;opacity:0;transform:translateY(10px);pointer-events:none;transition:.18s}
    #pricing-estimate-toast.show{opacity:1;transform:translateY(0)}#pricing-estimate-toast small{display:block;margin-top:3px;color:#d4d4d8;font-size:9px}
    @media(max-width:900px){#tool-pricing .pricing-row{grid-template-columns:24px minmax(170px,1fr) 86px 105px 58px 30px!important}.pr-estimate{padding:5px 4px!important}}
  `;document.head.appendChild(s)}
  function enhance(){const root=document.getElementById('tool-pricing');if(!root)return;root.querySelectorAll('.pricing-row').forEach(row=>{if(row.querySelector('.pr-estimate'))return;const del=row.querySelector('.del');if(!del)return;const b=document.createElement('button');b.type='button';b.className='pr-estimate';b.textContent='Odhad';b.title='Odhadne hodiny/cenu z ostatních položek a uložených nabídek';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();estimateRow(row)});del.before(b)})}
  function init(){injectStyle();enhance();const root=document.getElementById('tool-pricing');if(root)new MutationObserver(()=>requestAnimationFrame(enhance)).observe(root,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();