(()=>{
  const PROJECTS_STORE='toolbox.pricingOffer.projects.v346';
  const ACTIVE_STORE='toolbox.pricingOffer.active.v346';
  const RATE_STORE='toolbox.pricingOffer.rowRates.v350';
  const money=n=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0}).format(Number(n)||0);
  function projects(){try{return JSON.parse(localStorage.getItem(PROJECTS_STORE)||'[]')||[]}catch(_){return[]}}
  function rates(){try{return JSON.parse(localStorage.getItem(RATE_STORE)||'{}')||{}}catch(_){return{}}}
  function saveRates(x){localStorage.setItem(RATE_STORE,JSON.stringify(x))}
  function active(){const id=localStorage.getItem(ACTIVE_STORE);return {id,p:projects().find(x=>x.id===id)||null}}
  function key(pid,gid,iid){return `${pid}|${gid}|${iid}`}
  function effectiveRate(pid,g,it,map){const v=Number(map[key(pid,g.id,it.id)]);return Number.isFinite(v)&&v>=0?v:(Number(g.rate)||0)}
  function calcProject(p,map){let arch=0,prof=0,hours=0;for(const g of p?.data?.groups||[]){for(const it of g.items||[]){if(it.on===false)continue;if(g.mode==='hours'){const q=Number(it.qty)||0;hours+=q;arch+=q*effectiveRate(p.id,g,it,map)}else prof+=Number(it.price)||0}}const net=arch+prof,vat=net*(Number(p?.data?.vat)||0)/100;return {arch,prof,hours,net,vat,gross:net+vat}}
  function enhanceRows(){const {id,p}=active();if(!id||!p)return;const map=rates();document.querySelectorAll('#tool-pricing .pricing-group').forEach(sec=>{const g=p.data?.groups?.find(x=>String(x.id)===String(sec.dataset.g));if(!g||g.mode!=='hours')return;sec.querySelectorAll('.pricing-row').forEach(row=>{const it=g.items?.find(x=>String(x.id)===String(row.dataset.i));if(!it||row.querySelector('.pr-row-rate'))return;const qty=row.querySelector('.pr-qty');if(!qty)return;let rateCell=qty.nextElementSibling;if(!rateCell)return;const input=document.createElement('input');input.type='number';input.min='0';input.step='50';input.className='pr-row-rate';const k=key(id,g.id,it.id),has=Object.prototype.hasOwnProperty.call(map,k);input.value=has?map[k]:(Number(g.rate)||0);input.title='Sazba pro tento řádek. Když je stejná jako sazba sekce, používá se sazba sekce.';rateCell.replaceWith(input);input.addEventListener('change',()=>{const m=rates(),val=Number(input.value);if(!Number.isFinite(val)||val<0||val===Number(g.rate||0))delete m[k];else m[k]=val;saveRates(m);refreshTotals()});qty.addEventListener('change',()=>setTimeout(refreshTotals,0))})})}
  function refreshTotals(){const {id,p}=active();if(!id||!p)return;const map=rates(),s=calcProject(p,map);document.querySelectorAll('#tool-pricing .pricing-group').forEach(sec=>{const g=p.data?.groups?.find(x=>String(x.id)===String(sec.dataset.g));if(!g)return;let gt=0;sec.querySelectorAll('.pricing-row').forEach(row=>{const it=g.items?.find(x=>String(x.id)===String(row.dataset.i));if(!it||it.on===false)return;if(g.mode==='hours'){const q=Number(row.querySelector('.pr-qty')?.value??it.qty)||0;const r=Number(row.querySelector('.pr-row-rate')?.value);const rr=Number.isFinite(r)?r:effectiveRate(id,g,it,map);const total=q*rr;gt+=total;const sum=row.querySelector('.sum');if(sum)sum.textContent=money(total)}else gt+=Number(row.querySelector('.pr-price')?.value??it.price)||0});const strong=sec.querySelector('.pricing-group-head strong');if(strong)strong.textContent=money(gt)});
    const keyBoxes=[...document.querySelectorAll('#tool-pricing .pricing-key b')];if(keyBoxes[0])keyBoxes[0].textContent=`${s.hours} h`;if(keyBoxes[1])keyBoxes[1].textContent=money(s.arch);if(keyBoxes[2])keyBoxes[2].textContent=money(s.prof);if(keyBoxes[3])keyBoxes[3].textContent=money(s.net);if(keyBoxes[4])keyBoxes[4].textContent=money(s.gross);
    const sumRows=[...document.querySelectorAll('#tool-pricing .pricing-summary-row')];if(sumRows[0]?.querySelector('b'))sumRows[0].querySelector('b').textContent=money(s.arch);if(sumRows[1]?.querySelector('b'))sumRows[1].querySelector('b').textContent=money(s.prof);if(sumRows[2]?.querySelector('b'))sumRows[2].querySelector('b').textContent=money(s.net);if(sumRows[3]?.querySelector('b'))sumRows[3].querySelector('b').textContent=money(s.vat);if(sumRows[4]?.querySelector('b'))sumRows[4].querySelector('b').textContent=money(s.gross)}
  function refreshCards(){const map=rates();document.querySelectorAll('#tool-pricing .pricing-project-card').forEach(card=>{const p=projects().find(x=>x.id===card.dataset.id);const price=card.querySelector('.price');if(p&&price)price.textContent=money(calcProject(p,map).net)})}
  function style(){if(document.getElementById('pricing-row-rate-v350-style'))return;const s=document.createElement('style');s.id='pricing-row-rate-v350-style';s.textContent=`#tool-pricing .pr-row-rate{width:100%;min-width:0;text-align:right}#tool-pricing .pr-row-rate:not(:focus){background:#fffef3}`;document.head.appendChild(s)}
  function enhance(){style();enhanceRows();refreshTotals();refreshCards()}
  function init(){enhance();const root=document.getElementById('tool-pricing');if(root)new MutationObserver(()=>requestAnimationFrame(enhance)).observe(root,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();