import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {STLLoader} from 'three/addons/loaders/STLLoader.js';
import {OBJLoader} from 'three/addons/loaders/OBJLoader.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {STLExporter} from 'three/addons/exporters/STLExporter.js';

const $=id=>document.getElementById(id),viewport=$('viewport');
const scene=new THREE.Scene();scene.background=new THREE.Color(0xe9e9ea);
const camera=new THREE.PerspectiveCamera(45,1,1,200000);camera.position.set(4500,3500,4500);
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;viewport.appendChild(renderer.domElement);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.target.set(0,500,0);orbit.screenSpacePanning=true;
const transform=new TransformControls(camera,renderer.domElement);scene.add(transform);transform.setTranslationSnap(10);transform.setRotationSnap(THREE.MathUtils.degToRad(5));
const work=new THREE.Group();work.name='MODEL';scene.add(work);const helpers=new THREE.Group();scene.add(helpers);
const grid=new THREE.GridHelper(20000,100,0x999999,0xc8c8c8);scene.add(grid);const axes=new THREE.AxesHelper(1200);axes.position.y=2;scene.add(axes);
scene.add(new THREE.HemisphereLight(0xffffff,0x777777,2.4));const sun=new THREE.DirectionalLight(0xffffff,2.2);sun.position.set(6000,9000,5000);scene.add(sun);

const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),ground=new THREE.Plane(new THREE.Vector3(0,1,0),0);
let selected=null,history=[],redo=[],restoring=false,tool='select',sketchPts=[],toolStart=null,hoverPoint=null,previewLine=null,previewShape=null,pushState=null,measureStart=null;
const edgeMat=new THREE.LineBasicMaterial({color:0x303030});
const snapMarker=new THREE.Mesh(new THREE.SphereGeometry(22,16,10),new THREE.MeshBasicMaterial({color:0x111111,depthTest:false}));snapMarker.renderOrder=1000;snapMarker.visible=false;helpers.add(snapMarker);
const pointMarkers=new THREE.Group();helpers.add(pointMarkers);

function toast(t){const el=$('toast');el.textContent=t;el.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>el.classList.remove('show'),1500)}
function status(t,v='—'){$('statusText').textContent=t;$('statusValue').textContent=v}
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
(function loop(){orbit.update();renderer.render(scene,camera);requestAnimationFrame(loop)})();
function mat(color=0xc9c9c9,opacity=1){return new THREE.MeshStandardMaterial({color,roughness:.72,metalness:.03,side:THREE.DoubleSide,transparent:opacity<1,opacity})}
function addEdges(root){root.traverse?.(o=>{if(o.isMesh&&!o.userData.edgeHelper){const e=new THREE.LineSegments(new THREE.EdgesGeometry(o.geometry,18),edgeMat.clone());e.userData.edgeHelper=true;e.raycast=()=>{};o.add(e)}})}
function refreshEdges(){work.traverse(o=>{if(o.userData.edgeHelper)o.visible=$('edgesToggle').checked})}
function selectableRoot(o){while(o&&o.parent&&o.parent!==work)o=o.parent;return o?.parent===work?o:null}
function dims(o){const b=new THREE.Box3().setFromObject(o),s=new THREE.Vector3();b.getSize(s);return s}
function pushHistory(){if(restoring)return;history.push(work.clone(true));if(history.length>40)history.shift();redo=[]}
function restore(s){restoring=true;transform.detach();work.clear();s.children.forEach(c=>work.add(c.clone(true)));selected=null;syncPanel();updateStats();refreshEdges();restoring=false}
function undo(){if(!history.length)return;redo.push(work.clone(true));restore(history.pop())}function redoFn(){if(!redo.length)return;history.push(work.clone(true));restore(redo.pop())}
function addObject(o,name='Objekt',hist=true){if(hist)pushHistory();o.name=name;o.traverse?.(m=>{if(m.isMesh){m.castShadow=true;m.receiveShadow=true;if(!m.material)m.material=mat()}});addEdges(o);work.add(o);select(o);updateStats();refreshEdges()}
function addPrimitive(type){let g,n;if(type==='box'){g=new THREE.BoxGeometry(1000,1000,1000);n='Kvádr'}if(type==='cylinder'){g=new THREE.CylinderGeometry(500,500,1000,48);n='Válec'}if(type==='sphere'){g=new THREE.SphereGeometry(500,40,24);n='Koule'}if(type==='plane'){g=new THREE.BoxGeometry(1200,100,1200);n='Deska'}const m=new THREE.Mesh(g,mat());m.position.y=type==='plane'?50:500;addObject(m,n)}
function select(o){selected=o;transform.detach();if(o&&tool==='select')transform.attach(o);syncPanel()}
function syncPanel(){const p=$('objectPanel'),no=$('noSelection');p.hidden=!selected;no.hidden=!!selected;if(!selected){$('faceTools').hidden=true;return}const d=dims(selected);$('objName').value=selected.name||'Objekt';['dimX','dimY','dimZ'].forEach((id,i)=>$(id).value=d.getComponent(i).toFixed(1));['posX','posY','posZ'].forEach((id,i)=>$(id).value=selected.position.getComponent(i).toFixed(1));['rotX','rotY','rotZ'].forEach((id,i)=>$(id).value=THREE.MathUtils.radToDeg(selected.rotation.toArray()[i]).toFixed(1));let m=null;selected.traverse?.(o=>{if(!m&&o.isMesh&&!o.userData.edgeHelper)m=o});if(selected.isMesh)m=selected;if(m?.material?.color)$('objColor').value='#'+m.material.color.getHexString();$('faceTools').hidden=!selected.userData.isFace}
function setMode(mode){setTool('select');transform.setMode(mode);document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));if(selected)transform.attach(selected)}
transform.addEventListener('dragging-changed',e=>orbit.enabled=!e.value);transform.addEventListener('mouseDown',pushHistory);transform.addEventListener('objectChange',()=>{syncPanel();updateStats()});
function duplicate(){if(!selected)return;pushHistory();const c=selected.clone(true);c.position.x+=150;c.position.z+=150;c.name=(selected.name||'Objekt')+' kopie';work.add(c);select(c);updateStats()}
function del(){if(!selected)return;pushHistory();work.remove(selected);select(null);updateStats()}
function newModel(){if(work.children.length&&!confirm('Založit nový model a zahodit aktuální scénu?'))return;pushHistory();work.clear();select(null);resetToolState();updateStats();toast('Nový model')}
function fit(o){const b=new THREE.Box3().setFromObject(o),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);const d=Math.max(s.x,s.y,s.z,1000)*2.3;camera.position.set(c.x+d,c.y+d*.8,c.z+d);orbit.target.copy(c)}
async function openFile(file){if(!file)return;const ext=file.name.split('.').pop().toLowerCase(),buf=await file.arrayBuffer();try{let obj;if(ext==='stl')obj=new THREE.Mesh(new STLLoader().parse(buf),mat());else if(ext==='obj')obj=new OBJLoader().parse(new TextDecoder().decode(buf));else if(ext==='glb'||ext==='gltf'){const gltf=await new Promise((res,rej)=>new GLTFLoader().parse(buf,'',res,rej));obj=gltf.scene}else throw Error('Nepodporovaný formát');addObject(obj,file.name);fit(obj)}catch(e){alert('Model se nepodařilo načíst: '+e.message)}}
function exportStlBlob(){return new Blob([new STLExporter().parse(work,{binary:true})],{type:'model/stl'})}
function download(){if(!work.children.length)return toast('Model je prázdný');const b=exportStlBlob(),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='20-20-model.stl';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open('20-20-toolbox-transfer',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('files'))r.result.createObjectStore('files')};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function sendPrint(){if(!work.children.length)return toast('Model je prázdný');const db=await openDb(),blob=exportStlBlob();await new Promise((res,rej)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').put({blob,name:'20-20-modeler.stl',time:Date.now()},'modeler-to-print');tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});location.href='../index.html?tool=3dprint&import=modeler'}
function updateStats(){let meshes=0,tris=0;work.traverse(o=>{if(o.isMesh&&!o.userData.edgeHelper){meshes++;const g=o.geometry;tris+=g.index?g.index.count/3:(g.attributes.position?.count||0)/3}});$('stats').textContent=`${work.children.length} objektů · ${meshes} meshů · ${Math.round(tris).toLocaleString('cs-CZ')} trojúhelníků`}
function setView(v){const c=selected?new THREE.Box3().setFromObject(selected).getCenter(new THREE.Vector3()):new THREE.Vector3(0,500,0),d=5000;if(v==='top')camera.position.set(c.x,c.y+d,c.z+.01);if(v==='front')camera.position.set(c.x,c.y,c.z+d);if(v==='right')camera.position.set(c.x+d,c.y,c.z);if(v==='iso')camera.position.set(c.x+d,c.y+d*.75,c.z+d);orbit.target.copy(c);camera.lookAt(c)}

function screenPointer(e){const r=renderer.domElement.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1;ray.setFromCamera(pointer,camera)}
function endpointCandidates(){const pts=[];work.traverse(o=>{if(o.userData.shapePts){o.userData.shapePts.forEach(p=>{const v=new THREE.Vector3(p.x,0,p.y);o.localToWorld(v);pts.push(v)})}if(o.isMesh&&!o.userData.edgeHelper&&o.geometry?.attributes?.position&&pts.length<5000){const a=o.geometry.attributes.position,step=Math.max(1,Math.ceil(a.count/1000));for(let i=0;i<a.count&&pts.length<5000;i+=step){const v=new THREE.Vector3().fromBufferAttribute(a,i);o.localToWorld(v);pts.push(v)}}});return pts}
function nearestEndpoint(p){if(!$('endpointSnap').checked)return null;let best=null,bd=Number($('endpointRadius').value)||80;for(const c of endpointCandidates()){const d=c.distanceTo(p);if(d<bd){bd=d;best=c}}return best}
function applyOrtho(p,base){if(!$('orthoToggle').checked||!base)return p;const d=p.clone().sub(base);const len=Math.hypot(d.x,d.z);if(len<.001)return p;const step=THREE.MathUtils.degToRad(Number($('orthoAngle').value)||90),a=Math.atan2(d.z,d.x),q=Math.round(a/step)*step;return new THREE.Vector3(base.x+Math.cos(q)*len,p.y,base.z+Math.sin(q)*len)}
function snapPoint(raw,base=null){let p=raw.clone();const ep=nearestEndpoint(p);if(ep){p.copy(ep);snapMarker.position.copy(ep);snapMarker.visible=true;$('snapBadge').style.display='block';$('snapBadge').textContent='VRCHOL';}else{snapMarker.visible=false;$('snapBadge').style.display='none';if($('snapToggle').checked){const s=Number($('snapSize').value)||10;p.x=Math.round(p.x/s)*s;p.y=Math.round(p.y/s)*s;p.z=Math.round(p.z/s)*s}}p=applyOrtho(p,base);return p}
function groundPoint(e,base=null){screenPointer(e);const p=new THREE.Vector3();if(!ray.ray.intersectPlane(ground,p))return null;return snapPoint(p,base)}
function clearPreview(){[previewLine,previewShape].forEach(o=>{if(o)helpers.remove(o)});previewLine=previewShape=null}
function drawPointMarkers(){pointMarkers.clear();for(const p of sketchPts){const m=snapMarker.clone();m.material=snapMarker.material.clone();m.material.color.set(0x18181b);m.position.copy(p);m.visible=true;pointMarkers.add(m)}}
function linePreview(last){if(previewLine)helpers.remove(previewLine);if(!sketchPts.length||!last)return;const pts=[...sketchPts,last],g=new THREE.BufferGeometry().setFromPoints(pts);previewLine=new THREE.Line(g,new THREE.LineBasicMaterial({color:0xd97706,depthTest:false}));previewLine.renderOrder=999;helpers.add(previewLine)}
function rectPreview(a,b){if(previewShape)helpers.remove(previewShape);const pts=[a,new THREE.Vector3(b.x,0,a.z),b,new THREE.Vector3(a.x,0,b.z),a],g=new THREE.BufferGeometry().setFromPoints(pts);previewShape=new THREE.Line(g,new THREE.LineBasicMaterial({color:0xd97706,depthTest:false}));helpers.add(previewShape)}
function circlePreview(c,p){if(previewShape)helpers.remove(previewShape);const r=c.distanceTo(p),pts=[];for(let i=0;i<=64;i++){const a=i/64*Math.PI*2;pts.push(new THREE.Vector3(c.x+Math.cos(a)*r,0,c.z+Math.sin(a)*r))}previewShape=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0xd97706,depthTest:false}));helpers.add(previewShape)}
function shapeFromPts(arr){const s=new THREE.Shape();s.moveTo(arr[0].x,arr[0].y);for(let i=1;i<arr.length;i++)s.lineTo(arr[i].x,arr[i].y);s.closePath();return s}
function makeFace(points,name='Plocha'){if(points.length<3)return;const s=new THREE.Shape();s.moveTo(points[0].x,points[0].z);for(let i=1;i<points.length;i++)s.lineTo(points[i].x,points[i].z);s.closePath();const m=new THREE.Mesh(new THREE.ShapeGeometry(s),mat(0xf7f197,.92));m.rotation.x=-Math.PI/2;m.position.y=.5;m.userData.isFace=true;m.userData.shapePts=points.map(p=>({x:p.x,y:p.z}));addObject(m,name);resetToolState(false);return m}
function makeCircle(c,r){const pts=[];for(let i=0;i<48;i++){const a=i/48*Math.PI*2;pts.push(new THREE.Vector3(c.x+Math.cos(a)*r,0,c.z+Math.sin(a)*r))}makeFace(pts,'Kruhová plocha')}
function extrudeGeometry(face,height,ghost=false){const pts=face.userData.shapePts;if(!pts)return null;const g=new THREE.ExtrudeGeometry(shapeFromPts(pts),{depth:Math.max(.1,Math.abs(height)),bevelEnabled:false,curveSegments:32});const m=new THREE.Mesh(g,ghost?new THREE.MeshStandardMaterial({color:0xf7f197,transparent:true,opacity:.45,side:THREE.DoubleSide,depthWrite:false}):mat());m.rotation.x=height>=0?-Math.PI/2:Math.PI/2;m.position.copy(face.position);m.position.y=face.position.y;m.userData.sourceShapePts=pts.map(p=>({...p}));return m}
function commitPush(face,height){if(!face?.userData.isFace)return;pushHistory();const solid=extrudeGeometry(face,height,false);solid.name=(face.name||'Plocha')+' solid';work.remove(face);addObject(solid,solid.name,false);pushState=null;$('pushOverlay').style.display='none';toast(`Push/Pull ${height.toFixed(1)} mm`)}
function updatePushPreview(height){if(!pushState)return;if(pushState.ghost)helpers.remove(pushState.ghost);pushState.height=height;pushState.ghost=extrudeGeometry(pushState.face,height,true);helpers.add(pushState.ghost);$('pushOverlay').style.display='block';$('pushOverlayValue').textContent=`${height.toFixed(1)} mm`;status('Push/Pull · klikni pro potvrzení nebo Enter',`${height.toFixed(1)} mm`);$('exactA').value=height.toFixed(1)}
function resetToolState(keepTool=true){sketchPts=[];toolStart=null;measureStart=null;hoverPoint=null;clearPreview();pointMarkers.clear();snapMarker.visible=false;$('snapBadge').style.display='none';if(pushState?.ghost)helpers.remove(pushState.ghost);pushState=null;$('pushOverlay').style.display='none';if(!keepTool)setTool('select')}
function setExactUi(){const a=$('exactLabelA'),b=$('exactLabelB'),hint=$('exactHint');b.hidden=true;$('exactA').value='';$('exactB').value='';if(tool==='line'){a.childNodes[0].nodeValue='Délka [mm]';hint.textContent='Po prvním bodu zadej délku dalšího úseku.'}else if(tool==='rect'){a.childNodes[0].nodeValue='Šířka X [mm]';b.childNodes[0].nodeValue='Hloubka Z [mm]';b.hidden=false;hint.textContent='Po prvním bodu zadej přesný rozměr obdélníku.'}else if(tool==='circle'){a.childNodes[0].nodeValue='Poloměr [mm]';hint.textContent='Po určení středu zadej poloměr.'}else if(tool==='pushpull'){a.childNodes[0].nodeValue='Výška [mm]';hint.textContent='Vyber plochu a zadej přesnou výšku.'}else if(tool==='measure'){a.childNodes[0].nodeValue='Délka [mm]';hint.textContent='Měření je pouze informativní.'}else{a.childNodes[0].nodeValue='Hodnota [mm]';hint.textContent='Vyber kreslicí nástroj.'}}
function setTool(t){tool=t;resetToolState(true);transform.detach();document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));viewport.className='tool-'+t;$('toolBadge').textContent=({select:'VÝBĚR',line:'ČÁRA / POLYGON',rect:'OBDÉLNÍK',circle:'KRUH',measure:'MĚŘENÍ',pushpull:'PUSH / PULL'})[t]||t.toUpperCase();orbit.enabled=t==='select';if(t==='select'&&selected)transform.attach(selected);status(t==='select'?'Kliknutím vyber objekt':'Klikni do pracovní roviny');setExactUi()}
function applyExact(){const a=Number($('exactA').value),b=Number($('exactB').value);if(!Number.isFinite(a))return toast('Zadej číselnou hodnotu');if(tool==='line'){if(!sketchPts.length)return toast('Nejdřív klikni první bod');const base=sketchPts.at(-1),dir=hoverPoint?hoverPoint.clone().sub(base):new THREE.Vector3(1,0,0);dir.y=0;if(dir.lengthSq()<.001)dir.set(1,0,0);dir.normalize();let p=base.clone().add(dir.multiplyScalar(Math.abs(a)));p=applyOrtho(p,base);sketchPts.push(p);drawPointMarkers();linePreview(p);status('Přesný úsek přidán',`${a.toFixed(1)} mm`)}else if(tool==='rect'){if(!toolStart)return toast('Nejdřív klikni počáteční bod');if(!Number.isFinite(b))return toast('Zadej oba rozměry');makeFace([toolStart,new THREE.Vector3(toolStart.x+a,0,toolStart.z),new THREE.Vector3(toolStart.x+a,0,toolStart.z+b),new THREE.Vector3(toolStart.x,0,toolStart.z+b)],'Obdélníková plocha')}else if(tool==='circle'){if(!toolStart)return toast('Nejdřív klikni střed');makeCircle(toolStart,Math.abs(a))}else if(tool==='pushpull'){const f=pushState?.face||selected;if(!f?.userData.isFace)return toast('Vyber plochu');if(pushState?.ghost)helpers.remove(pushState.ghost);commitPush(f,a)}else toast('Pro tento nástroj není přesný vstup aktivní')}

renderer.domElement.addEventListener('pointermove',e=>{const base=tool==='line'&&sketchPts.length?sketchPts.at(-1):toolStart;const p=groundPoint(e,base);hoverPoint=p;if(tool==='line'&&p){linePreview(p);if(sketchPts.length)status('Další bod',`${sketchPts.at(-1).distanceTo(p).toFixed(1)} mm`)}if(tool==='rect'&&toolStart&&p){rectPreview(toolStart,p);status('Obdélník',`${Math.abs(p.x-toolStart.x).toFixed(1)} × ${Math.abs(p.z-toolStart.z).toFixed(1)} mm`)}if(tool==='circle'&&toolStart&&p){circlePreview(toolStart,p);status('Kruh',`R ${toolStart.distanceTo(p).toFixed(1)} mm`)}if(tool==='pushpull'&&pushState){const h=(pushState.startY-e.clientY)*10,s=Number($('snapSize').value)||10;updatePushPreview($('snapToggle').checked?Math.round(h/s)*s:h)}if(tool==='measure'&&measureStart&&p)status('Měření',`${measureStart.distanceTo(p).toFixed(1)} mm`)});
renderer.domElement.addEventListener('pointerdown',e=>{if(transform.dragging||e.button!==0)return;if(tool==='select'){screenPointer(e);const hits=ray.intersectObjects(work.children,true).filter(h=>!h.object.userData.edgeHelper);select(hits[0]?selectableRoot(hits[0].object):null);return}if(tool==='pushpull'){if(pushState){if(pushState.ghost)helpers.remove(pushState.ghost);commitPush(pushState.face,pushState.height||Number($('exactA').value)||100);return}screenPointer(e);const hits=ray.intersectObjects(work.children,true).filter(h=>selectableRoot(h.object)?.userData.isFace);const f=hits[0]?selectableRoot(hits[0].object):null;if(!f)return toast('Klikni na nakreslenou plochu');select(f);pushState={face:f,startY:e.clientY,height:0,ghost:null};updatePushPreview(0);return}const base=tool==='line'&&sketchPts.length?sketchPts.at(-1):toolStart,p=groundPoint(e,base);if(!p)return;if(tool==='line'){if(!sketchPts.length){sketchPts=[p];drawPointMarkers();status('První bod · pokračuj nebo zadej délku','0 mm');return}if(sketchPts.length>=3&&p.distanceTo(sketchPts[0])<Math.max(30,Number($('endpointRadius').value)||80)){makeFace([...sketchPts],'Polygon');return}sketchPts.push(p);drawPointMarkers();status('Bod přidán',`${sketchPts.at(-2).distanceTo(p).toFixed(1)} mm`)}else if(tool==='rect'){if(!toolStart){toolStart=p;sketchPts=[p];drawPointMarkers();status('Druhý roh nebo přesné X/Z');return}makeFace([toolStart,new THREE.Vector3(p.x,0,toolStart.z),p,new THREE.Vector3(toolStart.x,0,p.z)],'Obdélníková plocha')}else if(tool==='circle'){if(!toolStart){toolStart=p;sketchPts=[p];drawPointMarkers();status('Urči poloměr nebo jej zadej přesně');return}makeCircle(toolStart,toolStart.distanceTo(p))}else if(tool==='measure'){if(!measureStart){measureStart=p;sketchPts=[p];drawPointMarkers();status('Klikni druhý bod');return}const d=measureStart.distanceTo(p);$('measureOverlay').style.display='block';$('measureOverlay').textContent=`${d.toFixed(1)} mm`;status('Naměřeno',`${d.toFixed(1)} mm`);measureStart=null;sketchPts=[];pointMarkers.clear()}});

$('btnExactApply').onclick=applyExact;$('exactA').addEventListener('keydown',e=>{if(e.key==='Enter')applyExact()});$('exactB').addEventListener('keydown',e=>{if(e.key==='Enter')applyExact()});
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addPrimitive(b.dataset.add));document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
$('btnDuplicate').onclick=duplicate;$('btnDelete').onclick=del;$('btnUndo').onclick=undo;$('btnRedo').onclick=redoFn;$('btnNew').onclick=newModel;$('btnOpen').onclick=()=>$('fileOpen').click();$('fileOpen').onchange=()=>openFile($('fileOpen').files?.[0]);$('btnDownload').onclick=download;$('btnPrint').onclick=sendPrint;$('btnPushExact').onclick=()=>{if(selected?.userData.isFace)commitPush(selected,Number($('pushHeight').value)||1000)};$('btnFaceFromSelection').onclick=()=>{if(sketchPts.length>=3)makeFace(sketchPts,'Plocha');else toast('Nakresli alespoň 3 body')};
$('gridToggle').onchange=e=>grid.visible=e.target.checked;$('edgesToggle').onchange=refreshEdges;$('snapToggle').onchange=e=>transform.setTranslationSnap(e.target.checked?(Number($('snapSize').value)||10):null);$('snapSize').onchange=()=>transform.setTranslationSnap($('snapToggle').checked?(Number($('snapSize').value)||10):null);$('orthoToggle').onchange=e=>toast(e.target.checked?'ORTO zapnuto':'ORTO vypnuto');
$('objName').onchange=e=>{if(selected){pushHistory();selected.name=e.target.value||'Objekt'}};$('objColor').oninput=e=>{if(!selected)return;selected.traverse(o=>{if(o.isMesh&&!o.userData.edgeHelper&&o.material?.color)o.material.color.set(e.target.value)})};
['posX','posY','posZ'].forEach((id,i)=>$(id).onchange=e=>{if(!selected)return;pushHistory();selected.position.setComponent(i,Number(e.target.value)||0);syncPanel()});['rotX','rotY','rotZ'].forEach((id,i)=>$(id).onchange=e=>{if(!selected)return;pushHistory();selected.rotation.setComponent(i,THREE.MathUtils.degToRad(Number(e.target.value)||0));syncPanel()});['dimX','dimY','dimZ'].forEach((id,i)=>$(id).onchange=e=>{if(!selected)return;const d=dims(selected).getComponent(i),t=Math.max(.001,Number(e.target.value)||d);if(d>0){pushHistory();selected.scale.setComponent(i,selected.scale.getComponent(i)*(t/d));syncPanel()}});
addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName))return;const k=e.key.toLowerCase();if(k==='escape')setTool('select');if(k==='l')setTool('line');if(k==='b')setTool('rect');if(k==='c')setTool('circle');if(k==='m')setTool('measure');if(k==='p')setTool('pushpull');if(k==='o'){$('orthoToggle').checked=!$('orthoToggle').checked;toast($('orthoToggle').checked?'ORTO zapnuto':'ORTO vypnuto')}if(k==='w')setMode('translate');if(k==='e')setMode('rotate');if(k==='r')setMode('scale');if(e.key==='Delete')del();if((e.ctrlKey||e.metaKey)&&k==='d'){e.preventDefault();duplicate()}if((e.ctrlKey||e.metaKey)&&k==='z'){e.preventDefault();e.shiftKey?redoFn():undo()}});
updateStats();setTool('select');toast('3D Modeler V3.27 připraven');
